<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/BL2.php');
	include_once(__DIR__ . '/BL2_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('BL2');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'BL2';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`BL2`.`IDBL2`" => "IDBL2",
		"IF(    CHAR_LENGTH(if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),'')) || CHAR_LENGTH(if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), CONCAT_WS('',   if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),''), '-', if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), '') /* IDBL3 */" => "IDBL3",
		"DATE_FORMAT(`BL2`.`Ngaysinhhoat`, '%d/%m/%Y')" => "Ngaysinhhoat",
		"DATE_FORMAT(`BL2`.`Ngaybaotin`, '%d/%m/%Y')" => "Ngaybaotin",
		"IF(    CHAR_LENGTH(`TinBao1`.`TenTinbao`), CONCAT_WS('',   `TinBao1`.`TenTinbao`), '') /* Tinbao */" => "Tinbao",
		"IF(    CHAR_LENGTH(`XulyTin1`.`Xulytin`), CONCAT_WS('',   `XulyTin1`.`Xulytin`), '') /* Xylytin */" => "Xylytin",
		"IF(    CHAR_LENGTH(`Ketqua1`.`Ketqua`), CONCAT_WS('',   `Ketqua1`.`Ketqua`), '') /* Ketqua */" => "Ketqua",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`BL2`.`IDBL2`',
		2 => 2,
		3 => '`BL2`.`Ngaysinhhoat`',
		4 => '`BL2`.`Ngaybaotin`',
		5 => '`TinBao1`.`TenTinbao`',
		6 => '`XulyTin1`.`Xulytin`',
		7 => '`Ketqua1`.`Ketqua`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`BL2`.`IDBL2`" => "IDBL2",
		"IF(    CHAR_LENGTH(if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),'')) || CHAR_LENGTH(if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), CONCAT_WS('',   if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),''), '-', if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), '') /* IDBL3 */" => "IDBL3",
		"DATE_FORMAT(`BL2`.`Ngaysinhhoat`, '%d/%m/%Y')" => "Ngaysinhhoat",
		"DATE_FORMAT(`BL2`.`Ngaybaotin`, '%d/%m/%Y')" => "Ngaybaotin",
		"IF(    CHAR_LENGTH(`TinBao1`.`TenTinbao`), CONCAT_WS('',   `TinBao1`.`TenTinbao`), '') /* Tinbao */" => "Tinbao",
		"IF(    CHAR_LENGTH(`XulyTin1`.`Xulytin`), CONCAT_WS('',   `XulyTin1`.`Xulytin`), '') /* Xylytin */" => "Xylytin",
		"IF(    CHAR_LENGTH(`Ketqua1`.`Ketqua`), CONCAT_WS('',   `Ketqua1`.`Ketqua`), '') /* Ketqua */" => "Ketqua",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`BL2`.`IDBL2`" => "IDBL2",
		"IF(    CHAR_LENGTH(if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),'')) || CHAR_LENGTH(if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), CONCAT_WS('',   if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),''), '-', if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), '') /* IDBL3 */" => "IDBL3",
		"`BL2`.`Ngaysinhhoat`" => "Ngaysinhhoat",
		"`BL2`.`Ngaybaotin`" => "Ngaybaotin",
		"IF(    CHAR_LENGTH(`TinBao1`.`TenTinbao`), CONCAT_WS('',   `TinBao1`.`TenTinbao`), '') /* Tinbao */" => "Tinbao",
		"IF(    CHAR_LENGTH(`XulyTin1`.`Xulytin`), CONCAT_WS('',   `XulyTin1`.`Xulytin`), '') /* Xylytin */" => "Xylytin",
		"IF(    CHAR_LENGTH(`Ketqua1`.`Ketqua`), CONCAT_WS('',   `Ketqua1`.`Ketqua`), '') /* Ketqua */" => "Ketqua",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`BL2`.`IDBL2`" => "IDBL2",
		"IF(    CHAR_LENGTH(if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),'')) || CHAR_LENGTH(if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), CONCAT_WS('',   if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),''), '-', if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), '') /* IDBL3 */" => "IDBL3",
		"DATE_FORMAT(`BL2`.`Ngaysinhhoat`, '%d/%m/%Y')" => "Ngaysinhhoat",
		"DATE_FORMAT(`BL2`.`Ngaybaotin`, '%d/%m/%Y')" => "Ngaybaotin",
		"IF(    CHAR_LENGTH(`TinBao1`.`TenTinbao`), CONCAT_WS('',   `TinBao1`.`TenTinbao`), '') /* Tinbao */" => "Tinbao",
		"IF(    CHAR_LENGTH(`XulyTin1`.`Xulytin`), CONCAT_WS('',   `XulyTin1`.`Xulytin`), '') /* Xylytin */" => "Xylytin",
		"IF(    CHAR_LENGTH(`Ketqua1`.`Ketqua`), CONCAT_WS('',   `Ketqua1`.`Ketqua`), '') /* Ketqua */" => "Ketqua",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['IDBL3' => 'IDBL3', 'Tinbao' => 'Tinbao', 'Xylytin' => 'Xylytin', 'Ketqua' => 'Ketqua', ];

	$x->QueryFrom = "`BL2` LEFT JOIN `BL3` as BL31 ON `BL31`.`IDBL3`=`BL2`.`IDBL3` LEFT JOIN `TinBao` as TinBao1 ON `TinBao1`.`ID`=`BL2`.`Tinbao` LEFT JOIN `XulyTin` as XulyTin1 ON `XulyTin1`.`ID`=`BL2`.`Xylytin` LEFT JOIN `Ketqua` as Ketqua1 ON `Ketqua1`.`ID`=`BL2`.`Ketqua` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'BL2_view.php';
	$x->TableTitle = 'BL2';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`BL2`.`IDBL2`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['IDBL2', 'IDBL3', 'Ngaysinhhoat', 'Ngaybaotin', 'Tinbao', 'Xylytin', 'Ketqua', ];
	$x->ColFieldName = ['IDBL2', 'IDBL3', 'Ngaysinhhoat', 'Ngaybaotin', 'Tinbao', 'Xylytin', 'Ketqua', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/BL2_templateTV.html';
	$x->SelectedTemplate = 'templates/BL2_templateTVS.html';
	$x->TemplateDV = 'templates/BL2_templateDV.html';
	$x->TemplateDVP = 'templates/BL2_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: BL2_init
	$render = true;
	if(function_exists('BL2_init')) {
		$args = [];
		$render = BL2_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: BL2_header
	$headerCode = '';
	if(function_exists('BL2_header')) {
		$args = [];
		$headerCode = BL2_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: BL2_footer
	$footerCode = '';
	if(function_exists('BL2_footer')) {
		$args = [];
		$footerCode = BL2_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
