<?php

// Data functions (insert, update, delete, form) for table BL2

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function BL2_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('BL2');
	if(!$arrPerm['insert']) return false;

	$data = [
		'IDBL3' => Request::lookup('IDBL3', ''),
		'Ngaysinhhoat' => mysql_datetime(Request::val('Ngaysinhhoat', '')),
		'Ngaybaotin' => mysql_datetime(Request::val('Ngaybaotin', '')),
		'Tinbao' => Request::lookup('Tinbao', ''),
		'Xylytin' => Request::lookup('Xylytin', ''),
		'Ketqua' => Request::lookup('Ketqua', ''),
	];

	if($data['IDBL3'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'IDBL3': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: BL2_before_insert
	if(function_exists('BL2_before_insert')) {
		$args = [];
		if(!BL2_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('BL2', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('BL2', $recID, calculated_fields()['BL2']);

	// hook: BL2_after_insert
	if(function_exists('BL2_after_insert')) {
		$res = sql("SELECT * FROM `BL2` WHERE `IDBL2`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!BL2_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('BL2', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) BL2_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function BL2_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function BL2_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('BL2', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: BL2_before_delete
	if(function_exists('BL2_before_delete')) {
		$args = [];
		if(!BL2_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `BL2` WHERE `IDBL2`='{$selected_id}'", $eo);

	// hook: BL2_after_delete
	if(function_exists('BL2_after_delete')) {
		$args = [];
		BL2_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='BL2' AND `pkValue`='{$selected_id}'", $eo);
}

function BL2_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('BL2', $selected_id, 'edit')) return false;

	$data = [
		'IDBL3' => Request::lookup('IDBL3', ''),
		'Ngaysinhhoat' => mysql_datetime(Request::val('Ngaysinhhoat', '')),
		'Ngaybaotin' => mysql_datetime(Request::val('Ngaybaotin', '')),
		'Tinbao' => Request::lookup('Tinbao', ''),
		'Xylytin' => Request::lookup('Xylytin', ''),
		'Ketqua' => Request::lookup('Ketqua', ''),
	];

	if($data['IDBL3'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'IDBL3': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('BL2', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: BL2_before_update
	if(function_exists('BL2_before_update')) {
		$args = ['old_data' => $old_data];
		if(!BL2_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'BL2', 
		backtick_keys_once($set), 
		['`IDBL2`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="BL2_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('BL2', $data['selectedID'], calculated_fields()['BL2']);

	// hook: BL2_after_update
	if(function_exists('BL2_after_update')) {
		$res = sql("SELECT * FROM `BL2` WHERE `IDBL2`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['IDBL2'];
		$args = ['old_data' => $old_data];
		if(!BL2_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='BL2' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function BL2_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('BL2');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_IDBL3 = Request::val('filterer_IDBL3');
	$filterer_Tinbao = Request::val('filterer_Tinbao');
	$filterer_Xylytin = Request::val('filterer_Xylytin');
	$filterer_Ketqua = Request::val('filterer_Ketqua');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IDBL3
	$combo_IDBL3 = new DataCombo;
	// combobox: Tinbao
	$combo_Tinbao = new DataCombo;
	// combobox: Xylytin
	$combo_Xylytin = new DataCombo;
	// combobox: Ketqua
	$combo_Ketqua = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('BL2', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('BL2', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('BL2', $selected_id, 'delete');

		$res = sql("SELECT * FROM `BL2` WHERE `IDBL2`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'BL2_view.php', false);
		}
		$combo_IDBL3->SelectedData = $row['IDBL3'];
		$combo_Tinbao->SelectedData = $row['Tinbao'];
		$combo_Xylytin->SelectedData = $row['Xylytin'];
		$combo_Ketqua->SelectedData = $row['Ketqua'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_IDBL3->SelectedData = $filterer_IDBL3;
		$combo_Tinbao->SelectedData = $filterer_Tinbao;
		$combo_Xylytin->SelectedData = $filterer_Xylytin;
		$combo_Ketqua->SelectedData = $filterer_Ketqua;
	}
	$combo_IDBL3->HTML = '<span id="IDBL3-container' . $rnd1 . '"></span><input type="hidden" name="IDBL3" id="IDBL3' . $rnd1 . '" value="' . html_attr($combo_IDBL3->SelectedData) . '">';
	$combo_IDBL3->MatchText = '<span id="IDBL3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IDBL3" id="IDBL3' . $rnd1 . '" value="' . html_attr($combo_IDBL3->SelectedData) . '">';
	$combo_Tinbao->HTML = '<span id="Tinbao-container' . $rnd1 . '"></span><input type="hidden" name="Tinbao" id="Tinbao' . $rnd1 . '" value="' . html_attr($combo_Tinbao->SelectedData) . '">';
	$combo_Tinbao->MatchText = '<span id="Tinbao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Tinbao" id="Tinbao' . $rnd1 . '" value="' . html_attr($combo_Tinbao->SelectedData) . '">';
	$combo_Xylytin->HTML = '<span id="Xylytin-container' . $rnd1 . '"></span><input type="hidden" name="Xylytin" id="Xylytin' . $rnd1 . '" value="' . html_attr($combo_Xylytin->SelectedData) . '">';
	$combo_Xylytin->MatchText = '<span id="Xylytin-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Xylytin" id="Xylytin' . $rnd1 . '" value="' . html_attr($combo_Xylytin->SelectedData) . '">';
	$combo_Ketqua->HTML = '<span id="Ketqua-container' . $rnd1 . '"></span><input type="hidden" name="Ketqua" id="Ketqua' . $rnd1 . '" value="' . html_attr($combo_Ketqua->SelectedData) . '">';
	$combo_Ketqua->MatchText = '<span id="Ketqua-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Ketqua" id="Ketqua' . $rnd1 . '" value="' . html_attr($combo_Ketqua->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_IDBL3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IDBL3'] : htmlspecialchars($filterer_IDBL3, ENT_QUOTES)); ?>"};
		AppGini.current_Tinbao__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Tinbao'] : htmlspecialchars($filterer_Tinbao, ENT_QUOTES)); ?>"};
		AppGini.current_Xylytin__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Xylytin'] : htmlspecialchars($filterer_Xylytin, ENT_QUOTES)); ?>"};
		AppGini.current_Ketqua__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Ketqua'] : htmlspecialchars($filterer_Ketqua, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(IDBL3_reload__RAND__) == 'function') IDBL3_reload__RAND__();
				if(typeof(Tinbao_reload__RAND__) == 'function') Tinbao_reload__RAND__();
				if(typeof(Xylytin_reload__RAND__) == 'function') Xylytin_reload__RAND__();
				if(typeof(Ketqua_reload__RAND__) == 'function') Ketqua_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function IDBL3_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#IDBL3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_IDBL3__RAND__.value, t: 'BL2', f: 'IDBL3' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="IDBL3"]').val(resp.results[0].id);
							$j('[id=IDBL3-container-readonly__RAND__]').html('<span class="match-text" id="IDBL3-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=BL3_view_parent]').hide(); } else { $j('.btn[id=BL3_view_parent]').show(); }


							if(typeof(IDBL3_update_autofills__RAND__) == 'function') IDBL3_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL2', f: 'IDBL3' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_IDBL3__RAND__.value = e.added.id;
				AppGini.current_IDBL3__RAND__.text = e.added.text;
				$j('[name="IDBL3"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=BL3_view_parent]').hide(); } else { $j('.btn[id=BL3_view_parent]').show(); }


				if(typeof(IDBL3_update_autofills__RAND__) == 'function') IDBL3_update_autofills__RAND__();
			});

			if(!$j("#IDBL3-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_IDBL3__RAND__.value, t: 'BL2', f: 'IDBL3' },
					success: function(resp) {
						$j('[name="IDBL3"]').val(resp.results[0].id);
						$j('[id=IDBL3-container-readonly__RAND__]').html('<span class="match-text" id="IDBL3-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=BL3_view_parent]').hide(); } else { $j('.btn[id=BL3_view_parent]').show(); }

						if(typeof(IDBL3_update_autofills__RAND__) == 'function') IDBL3_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_IDBL3__RAND__.value, t: 'BL2', f: 'IDBL3' },
				success: function(resp) {
					$j('[id=IDBL3-container__RAND__], [id=IDBL3-container-readonly__RAND__]').html('<span class="match-text" id="IDBL3-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=BL3_view_parent]').hide(); } else { $j('.btn[id=BL3_view_parent]').show(); }

					if(typeof(IDBL3_update_autofills__RAND__) == 'function') IDBL3_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Tinbao_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Tinbao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Tinbao__RAND__.value, t: 'BL2', f: 'Tinbao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Tinbao"]').val(resp.results[0].id);
							$j('[id=Tinbao-container-readonly__RAND__]').html('<span class="match-text" id="Tinbao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TinBao_view_parent]').hide(); } else { $j('.btn[id=TinBao_view_parent]').show(); }


							if(typeof(Tinbao_update_autofills__RAND__) == 'function') Tinbao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL2', f: 'Tinbao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Tinbao__RAND__.value = e.added.id;
				AppGini.current_Tinbao__RAND__.text = e.added.text;
				$j('[name="Tinbao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TinBao_view_parent]').hide(); } else { $j('.btn[id=TinBao_view_parent]').show(); }


				if(typeof(Tinbao_update_autofills__RAND__) == 'function') Tinbao_update_autofills__RAND__();
			});

			if(!$j("#Tinbao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Tinbao__RAND__.value, t: 'BL2', f: 'Tinbao' },
					success: function(resp) {
						$j('[name="Tinbao"]').val(resp.results[0].id);
						$j('[id=Tinbao-container-readonly__RAND__]').html('<span class="match-text" id="Tinbao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TinBao_view_parent]').hide(); } else { $j('.btn[id=TinBao_view_parent]').show(); }

						if(typeof(Tinbao_update_autofills__RAND__) == 'function') Tinbao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Tinbao__RAND__.value, t: 'BL2', f: 'Tinbao' },
				success: function(resp) {
					$j('[id=Tinbao-container__RAND__], [id=Tinbao-container-readonly__RAND__]').html('<span class="match-text" id="Tinbao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=TinBao_view_parent]').hide(); } else { $j('.btn[id=TinBao_view_parent]').show(); }

					if(typeof(Tinbao_update_autofills__RAND__) == 'function') Tinbao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Xylytin_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Xylytin-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Xylytin__RAND__.value, t: 'BL2', f: 'Xylytin' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Xylytin"]').val(resp.results[0].id);
							$j('[id=Xylytin-container-readonly__RAND__]').html('<span class="match-text" id="Xylytin-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=XulyTin_view_parent]').hide(); } else { $j('.btn[id=XulyTin_view_parent]').show(); }


							if(typeof(Xylytin_update_autofills__RAND__) == 'function') Xylytin_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL2', f: 'Xylytin' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Xylytin__RAND__.value = e.added.id;
				AppGini.current_Xylytin__RAND__.text = e.added.text;
				$j('[name="Xylytin"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=XulyTin_view_parent]').hide(); } else { $j('.btn[id=XulyTin_view_parent]').show(); }


				if(typeof(Xylytin_update_autofills__RAND__) == 'function') Xylytin_update_autofills__RAND__();
			});

			if(!$j("#Xylytin-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Xylytin__RAND__.value, t: 'BL2', f: 'Xylytin' },
					success: function(resp) {
						$j('[name="Xylytin"]').val(resp.results[0].id);
						$j('[id=Xylytin-container-readonly__RAND__]').html('<span class="match-text" id="Xylytin-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=XulyTin_view_parent]').hide(); } else { $j('.btn[id=XulyTin_view_parent]').show(); }

						if(typeof(Xylytin_update_autofills__RAND__) == 'function') Xylytin_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Xylytin__RAND__.value, t: 'BL2', f: 'Xylytin' },
				success: function(resp) {
					$j('[id=Xylytin-container__RAND__], [id=Xylytin-container-readonly__RAND__]').html('<span class="match-text" id="Xylytin-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=XulyTin_view_parent]').hide(); } else { $j('.btn[id=XulyTin_view_parent]').show(); }

					if(typeof(Xylytin_update_autofills__RAND__) == 'function') Xylytin_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Ketqua_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Ketqua-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Ketqua__RAND__.value, t: 'BL2', f: 'Ketqua' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Ketqua"]').val(resp.results[0].id);
							$j('[id=Ketqua-container-readonly__RAND__]').html('<span class="match-text" id="Ketqua-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Ketqua_view_parent]').hide(); } else { $j('.btn[id=Ketqua_view_parent]').show(); }


							if(typeof(Ketqua_update_autofills__RAND__) == 'function') Ketqua_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL2', f: 'Ketqua' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Ketqua__RAND__.value = e.added.id;
				AppGini.current_Ketqua__RAND__.text = e.added.text;
				$j('[name="Ketqua"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Ketqua_view_parent]').hide(); } else { $j('.btn[id=Ketqua_view_parent]').show(); }


				if(typeof(Ketqua_update_autofills__RAND__) == 'function') Ketqua_update_autofills__RAND__();
			});

			if(!$j("#Ketqua-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Ketqua__RAND__.value, t: 'BL2', f: 'Ketqua' },
					success: function(resp) {
						$j('[name="Ketqua"]').val(resp.results[0].id);
						$j('[id=Ketqua-container-readonly__RAND__]').html('<span class="match-text" id="Ketqua-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Ketqua_view_parent]').hide(); } else { $j('.btn[id=Ketqua_view_parent]').show(); }

						if(typeof(Ketqua_update_autofills__RAND__) == 'function') Ketqua_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Ketqua__RAND__.value, t: 'BL2', f: 'Ketqua' },
				success: function(resp) {
					$j('[id=Ketqua-container__RAND__], [id=Ketqua-container-readonly__RAND__]').html('<span class="match-text" id="Ketqua-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Ketqua_view_parent]').hide(); } else { $j('.btn[id=Ketqua_view_parent]').show(); }

					if(typeof(Ketqua_update_autofills__RAND__) == 'function') Ketqua_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/BL2_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/BL2_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'BL2 details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return BL2_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return BL2_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return BL2_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#IDBL3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IDBL3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Ngaysinhhoat').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaysinhhoat\">' + (jQuery('#Ngaysinhhoat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Ngaybaotin').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaybaotin\">' + (jQuery('#Ngaybaotin').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Tinbao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Tinbao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Xylytin').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Xylytin_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Ketqua').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Ketqua_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaysinhhoat').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaybaotin').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(IDBL3)%%>', $combo_IDBL3->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(IDBL3)%%>', $combo_IDBL3->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(IDBL3)%%>', urlencode($combo_IDBL3->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Tinbao)%%>', $combo_Tinbao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Tinbao)%%>', $combo_Tinbao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Tinbao)%%>', urlencode($combo_Tinbao->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Xylytin)%%>', $combo_Xylytin->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Xylytin)%%>', $combo_Xylytin->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Xylytin)%%>', urlencode($combo_Xylytin->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Ketqua)%%>', $combo_Ketqua->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Ketqua)%%>', $combo_Ketqua->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Ketqua)%%>', urlencode($combo_Ketqua->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['IDBL3' => ['BL3', 'IDBL3'], 'Tinbao' => ['TinBao', 'Tinbao'], 'Xylytin' => ['XulyTin', 'Xylytin'], 'Ketqua' => ['Ketqua', 'Ketqua'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(IDBL2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(IDBL3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaysinhhoat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaybaotin)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Tinbao)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Xylytin)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ketqua)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDBL2)%%>', safe_html($urow['IDBL2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDBL2)%%>', html_attr($row['IDBL2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL2)%%>', urlencode($urow['IDBL2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDBL3)%%>', safe_html($urow['IDBL3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDBL3)%%>', html_attr($row['IDBL3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL3)%%>', urlencode($urow['IDBL3']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaysinhhoat)%%>', app_datetime($row['Ngaysinhhoat'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaysinhhoat)%%>', urlencode(app_datetime($urow['Ngaysinhhoat'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaybaotin)%%>', app_datetime($row['Ngaybaotin'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaybaotin)%%>', urlencode(app_datetime($urow['Ngaybaotin'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Tinbao)%%>', safe_html($urow['Tinbao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Tinbao)%%>', html_attr($row['Tinbao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tinbao)%%>', urlencode($urow['Tinbao']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Xylytin)%%>', safe_html($urow['Xylytin']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Xylytin)%%>', html_attr($row['Xylytin']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Xylytin)%%>', urlencode($urow['Xylytin']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Ketqua)%%>', safe_html($urow['Ketqua']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Ketqua)%%>', html_attr($row['Ketqua']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ketqua)%%>', urlencode($urow['Ketqua']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(IDBL2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(IDBL3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaysinhhoat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaysinhhoat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaybaotin)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaybaotin)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Tinbao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tinbao)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Xylytin)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Xylytin)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ketqua)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ketqua)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('BL2');
	if($selected_id) {
		$jdata = get_joined_record('BL2', $selected_id);
		if($jdata === false) $jdata = get_defaults('BL2');
		$rdata = $row;
	}
	$templateCode .= loadView('BL2-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: BL2_dv
	if(function_exists('BL2_dv')) {
		$args = [];
		BL2_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}