<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/BL3.php');
	include_once(__DIR__ . '/BL3_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('BL3');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'BL3';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`BL3`.`IDBL3`" => "IDBL3",
		"IF(    CHAR_LENGTH(`CTV1`.`Bidanh`), CONCAT_WS('',   `CTV1`.`Bidanh`), '') /* IDCTV */" => "IDCTV",
		"DATE_FORMAT(`BL3`.`Ngaydauki`, '%d/%m/%Y')" => "Ngaydauki",
		"DATE_FORMAT(`BL3`.`Ngaycuoiki`, '%d/%m/%Y')" => "Ngaycuoiki",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV1`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV1`.`Phanloai`), '') /* CBPhanloai */" => "CBPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV2`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV2`.`Phanloai`), '') /* CHPhanloai */" => "CHPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV3`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV3`.`Phanloai`), '') /* Phanloai */" => "Phanloai",
		"`BL3`.`Nx_Dx`" => "Nx_Dx",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`BL3`.`IDBL3`',
		2 => '`CTV1`.`Bidanh`',
		3 => '`BL3`.`Ngaydauki`',
		4 => '`BL3`.`Ngaycuoiki`',
		5 => '`PhanLoai_CTV1`.`Phanloai`',
		6 => '`PhanLoai_CTV2`.`Phanloai`',
		7 => '`PhanLoai_CTV3`.`Phanloai`',
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`BL3`.`IDBL3`" => "IDBL3",
		"IF(    CHAR_LENGTH(`CTV1`.`Bidanh`), CONCAT_WS('',   `CTV1`.`Bidanh`), '') /* IDCTV */" => "IDCTV",
		"DATE_FORMAT(`BL3`.`Ngaydauki`, '%d/%m/%Y')" => "Ngaydauki",
		"DATE_FORMAT(`BL3`.`Ngaycuoiki`, '%d/%m/%Y')" => "Ngaycuoiki",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV1`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV1`.`Phanloai`), '') /* CBPhanloai */" => "CBPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV2`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV2`.`Phanloai`), '') /* CHPhanloai */" => "CHPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV3`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV3`.`Phanloai`), '') /* Phanloai */" => "Phanloai",
		"`BL3`.`Nx_Dx`" => "Nx_Dx",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`BL3`.`IDBL3`" => "ID",
		"IF(    CHAR_LENGTH(`CTV1`.`Bidanh`), CONCAT_WS('',   `CTV1`.`Bidanh`), '') /* IDCTV */" => "IDCTV",
		"`BL3`.`Ngaydauki`" => "Ngaydauki",
		"`BL3`.`Ngaycuoiki`" => "Ngaycuoiki",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV1`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV1`.`Phanloai`), '') /* CBPhanloai */" => "CBPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV2`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV2`.`Phanloai`), '') /* CHPhanloai */" => "CHPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV3`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV3`.`Phanloai`), '') /* Phanloai */" => "Phanloai",
		"`BL3`.`Nx_Dx`" => "Nx Dx",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`BL3`.`IDBL3`" => "IDBL3",
		"IF(    CHAR_LENGTH(`CTV1`.`Bidanh`), CONCAT_WS('',   `CTV1`.`Bidanh`), '') /* IDCTV */" => "IDCTV",
		"DATE_FORMAT(`BL3`.`Ngaydauki`, '%d/%m/%Y')" => "Ngaydauki",
		"DATE_FORMAT(`BL3`.`Ngaycuoiki`, '%d/%m/%Y')" => "Ngaycuoiki",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV1`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV1`.`Phanloai`), '') /* CBPhanloai */" => "CBPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV2`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV2`.`Phanloai`), '') /* CHPhanloai */" => "CHPhanloai",
		"IF(    CHAR_LENGTH(`PhanLoai_CTV3`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV3`.`Phanloai`), '') /* Phanloai */" => "Phanloai",
		"`BL3`.`Nx_Dx`" => "Nx_Dx",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['IDCTV' => 'IDCTV', 'CBPhanloai' => 'CBPhanloai', 'CHPhanloai' => 'CHPhanloai', 'Phanloai' => 'Phanloai', ];

	$x->QueryFrom = "`BL3` LEFT JOIN `CTV` as CTV1 ON `CTV1`.`IDCTV`=`BL3`.`IDCTV` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV1 ON `PhanLoai_CTV1`.`ID`=`BL3`.`CBPhanloai` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV2 ON `PhanLoai_CTV2`.`ID`=`BL3`.`CHPhanloai` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV3 ON `PhanLoai_CTV3`.`ID`=`BL3`.`Phanloai` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'BL3_view.php';
	$x->TableTitle = 'BL3';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`BL3`.`IDBL3`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'IDCTV', 'Ngaydauki', 'Ngaycuoiki', 'CBPhanloai', 'CHPhanloai', 'Phanloai', 'Nx Dx', ];
	$x->ColFieldName = ['IDBL3', 'IDCTV', 'Ngaydauki', 'Ngaycuoiki', 'CBPhanloai', 'CHPhanloai', 'Phanloai', 'Nx_Dx', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/BL3_templateTV.html';
	$x->SelectedTemplate = 'templates/BL3_templateTVS.html';
	$x->TemplateDV = 'templates/BL3_templateDV.html';
	$x->TemplateDVP = 'templates/BL3_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: BL3_init
	$render = true;
	if(function_exists('BL3_init')) {
		$args = [];
		$render = BL3_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: BL3_header
	$headerCode = '';
	if(function_exists('BL3_header')) {
		$args = [];
		$headerCode = BL3_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: BL3_footer
	$footerCode = '';
	if(function_exists('BL3_footer')) {
		$args = [];
		$footerCode = BL3_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
