<?php

// Data functions (insert, update, delete, form) for table BL3

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function BL3_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('BL3');
	if(!$arrPerm['insert']) return false;

	$data = [
		'IDCTV' => Request::lookup('IDCTV', ''),
		'Ngaydauki' => mysql_datetime(Request::val('Ngaydauki', '')),
		'Ngaycuoiki' => mysql_datetime(Request::val('Ngaycuoiki', '')),
		'CBPhanloai' => Request::lookup('CBPhanloai', ''),
		'CHPhanloai' => Request::lookup('CHPhanloai', ''),
		'Phanloai' => Request::lookup('Phanloai', ''),
		'Nx_Dx' => Request::val('Nx_Dx', ''),
	];

	if($data['IDCTV'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'IDCTV': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: BL3_before_insert
	if(function_exists('BL3_before_insert')) {
		$args = [];
		if(!BL3_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('BL3', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('BL3', $recID, calculated_fields()['BL3']);

	// hook: BL3_after_insert
	if(function_exists('BL3_after_insert')) {
		$res = sql("SELECT * FROM `BL3` WHERE `IDBL3`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!BL3_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('BL3', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) BL3_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function BL3_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// copy BL2
	$res = sql("SELECT * FROM `BL2` WHERE `IDBL3`='{$safe_sid}'", $eo);
	while($row = db_fetch_assoc($res)) {
		$data = [
			'SelectedID' => $row['IDBL2'],
			'IDBL3' => $destination_id,
			'Ngaysinhhoat' => $row['Ngaysinhhoat'],
			'Ngaybaotin' => $row['Ngaybaotin'],
			'Tinbao' => $row['Tinbao'],
			'Xylytin' => $row['Xylytin'],
			'Ketqua' => $row['Ketqua'],
		];

		$ch = curl_insert_handler('BL2', $data);
		if($ch !== false) $requests[] = $ch;
	}

	// launch requests, asynchronously
	curl_batch($requests);
}

function BL3_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('BL3', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: BL3_before_delete
	if(function_exists('BL3_before_delete')) {
		$args = [];
		if(!BL3_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: BL2
	$res = sql("SELECT `IDBL3` FROM `BL3` WHERE `IDBL3`='{$selected_id}'", $eo);
	$IDBL3 = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `BL2` WHERE `IDBL3`='" . makeSafe($IDBL3[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'BL2', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'BL2', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'BL3_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'BL3_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `BL3` WHERE `IDBL3`='{$selected_id}'", $eo);

	// hook: BL3_after_delete
	if(function_exists('BL3_after_delete')) {
		$args = [];
		BL3_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='BL3' AND `pkValue`='{$selected_id}'", $eo);
}

function BL3_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('BL3', $selected_id, 'edit')) return false;

	$data = [
		'IDCTV' => Request::lookup('IDCTV', ''),
		'Ngaydauki' => mysql_datetime(Request::val('Ngaydauki', '')),
		'Ngaycuoiki' => mysql_datetime(Request::val('Ngaycuoiki', '')),
		'CBPhanloai' => Request::lookup('CBPhanloai', ''),
		'CHPhanloai' => Request::lookup('CHPhanloai', ''),
		'Phanloai' => Request::lookup('Phanloai', ''),
		'Nx_Dx' => Request::val('Nx_Dx', ''),
	];

	if($data['IDCTV'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'IDCTV': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('BL3', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: BL3_before_update
	if(function_exists('BL3_before_update')) {
		$args = ['old_data' => $old_data];
		if(!BL3_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'BL3', 
		backtick_keys_once($set), 
		['`IDBL3`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="BL3_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('BL3', $data['selectedID'], calculated_fields()['BL3']);

	// hook: BL3_after_update
	if(function_exists('BL3_after_update')) {
		$res = sql("SELECT * FROM `BL3` WHERE `IDBL3`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['IDBL3'];
		$args = ['old_data' => $old_data];
		if(!BL3_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='BL3' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function BL3_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('BL3');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_IDCTV = Request::val('filterer_IDCTV');
	$filterer_CBPhanloai = Request::val('filterer_CBPhanloai');
	$filterer_CHPhanloai = Request::val('filterer_CHPhanloai');
	$filterer_Phanloai = Request::val('filterer_Phanloai');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: IDCTV
	$combo_IDCTV = new DataCombo;
	// combobox: CBPhanloai
	$combo_CBPhanloai = new DataCombo;
	// combobox: CHPhanloai
	$combo_CHPhanloai = new DataCombo;
	// combobox: Phanloai
	$combo_Phanloai = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('BL3', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('BL3', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('BL3', $selected_id, 'delete');

		$res = sql("SELECT * FROM `BL3` WHERE `IDBL3`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'BL3_view.php', false);
		}
		$combo_IDCTV->SelectedData = $row['IDCTV'];
		$combo_CBPhanloai->SelectedData = $row['CBPhanloai'];
		$combo_CHPhanloai->SelectedData = $row['CHPhanloai'];
		$combo_Phanloai->SelectedData = $row['Phanloai'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_IDCTV->SelectedData = $filterer_IDCTV;
		$combo_CBPhanloai->SelectedData = $filterer_CBPhanloai;
		$combo_CHPhanloai->SelectedData = $filterer_CHPhanloai;
		$combo_Phanloai->SelectedData = $filterer_Phanloai;
	}
	$combo_IDCTV->HTML = '<span id="IDCTV-container' . $rnd1 . '"></span><input type="hidden" name="IDCTV" id="IDCTV' . $rnd1 . '" value="' . html_attr($combo_IDCTV->SelectedData) . '">';
	$combo_IDCTV->MatchText = '<span id="IDCTV-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IDCTV" id="IDCTV' . $rnd1 . '" value="' . html_attr($combo_IDCTV->SelectedData) . '">';
	$combo_CBPhanloai->HTML = '<span id="CBPhanloai-container' . $rnd1 . '"></span><input type="hidden" name="CBPhanloai" id="CBPhanloai' . $rnd1 . '" value="' . html_attr($combo_CBPhanloai->SelectedData) . '">';
	$combo_CBPhanloai->MatchText = '<span id="CBPhanloai-container-readonly' . $rnd1 . '"></span><input type="hidden" name="CBPhanloai" id="CBPhanloai' . $rnd1 . '" value="' . html_attr($combo_CBPhanloai->SelectedData) . '">';
	$combo_CHPhanloai->HTML = '<span id="CHPhanloai-container' . $rnd1 . '"></span><input type="hidden" name="CHPhanloai" id="CHPhanloai' . $rnd1 . '" value="' . html_attr($combo_CHPhanloai->SelectedData) . '">';
	$combo_CHPhanloai->MatchText = '<span id="CHPhanloai-container-readonly' . $rnd1 . '"></span><input type="hidden" name="CHPhanloai" id="CHPhanloai' . $rnd1 . '" value="' . html_attr($combo_CHPhanloai->SelectedData) . '">';
	$combo_Phanloai->HTML = '<span id="Phanloai-container' . $rnd1 . '"></span><input type="hidden" name="Phanloai" id="Phanloai' . $rnd1 . '" value="' . html_attr($combo_Phanloai->SelectedData) . '">';
	$combo_Phanloai->MatchText = '<span id="Phanloai-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Phanloai" id="Phanloai' . $rnd1 . '" value="' . html_attr($combo_Phanloai->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_IDCTV__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IDCTV'] : htmlspecialchars($filterer_IDCTV, ENT_QUOTES)); ?>"};
		AppGini.current_CBPhanloai__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['CBPhanloai'] : htmlspecialchars($filterer_CBPhanloai, ENT_QUOTES)); ?>"};
		AppGini.current_CHPhanloai__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['CHPhanloai'] : htmlspecialchars($filterer_CHPhanloai, ENT_QUOTES)); ?>"};
		AppGini.current_Phanloai__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Phanloai'] : htmlspecialchars($filterer_Phanloai, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(IDCTV_reload__RAND__) == 'function') IDCTV_reload__RAND__();
				if(typeof(CBPhanloai_reload__RAND__) == 'function') CBPhanloai_reload__RAND__();
				if(typeof(CHPhanloai_reload__RAND__) == 'function') CHPhanloai_reload__RAND__();
				if(typeof(Phanloai_reload__RAND__) == 'function') Phanloai_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function IDCTV_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#IDCTV-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_IDCTV__RAND__.value, t: 'BL3', f: 'IDCTV' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="IDCTV"]').val(resp.results[0].id);
							$j('[id=IDCTV-container-readonly__RAND__]').html('<span class="match-text" id="IDCTV-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=CTV_view_parent]').hide(); } else { $j('.btn[id=CTV_view_parent]').show(); }


							if(typeof(IDCTV_update_autofills__RAND__) == 'function') IDCTV_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL3', f: 'IDCTV' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_IDCTV__RAND__.value = e.added.id;
				AppGini.current_IDCTV__RAND__.text = e.added.text;
				$j('[name="IDCTV"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=CTV_view_parent]').hide(); } else { $j('.btn[id=CTV_view_parent]').show(); }


				if(typeof(IDCTV_update_autofills__RAND__) == 'function') IDCTV_update_autofills__RAND__();
			});

			if(!$j("#IDCTV-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_IDCTV__RAND__.value, t: 'BL3', f: 'IDCTV' },
					success: function(resp) {
						$j('[name="IDCTV"]').val(resp.results[0].id);
						$j('[id=IDCTV-container-readonly__RAND__]').html('<span class="match-text" id="IDCTV-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=CTV_view_parent]').hide(); } else { $j('.btn[id=CTV_view_parent]').show(); }

						if(typeof(IDCTV_update_autofills__RAND__) == 'function') IDCTV_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_IDCTV__RAND__.value, t: 'BL3', f: 'IDCTV' },
				success: function(resp) {
					$j('[id=IDCTV-container__RAND__], [id=IDCTV-container-readonly__RAND__]').html('<span class="match-text" id="IDCTV-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=CTV_view_parent]').hide(); } else { $j('.btn[id=CTV_view_parent]').show(); }

					if(typeof(IDCTV_update_autofills__RAND__) == 'function') IDCTV_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function CBPhanloai_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#CBPhanloai-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_CBPhanloai__RAND__.value, t: 'BL3', f: 'CBPhanloai' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="CBPhanloai"]').val(resp.results[0].id);
							$j('[id=CBPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CBPhanloai-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


							if(typeof(CBPhanloai_update_autofills__RAND__) == 'function') CBPhanloai_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL3', f: 'CBPhanloai' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_CBPhanloai__RAND__.value = e.added.id;
				AppGini.current_CBPhanloai__RAND__.text = e.added.text;
				$j('[name="CBPhanloai"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


				if(typeof(CBPhanloai_update_autofills__RAND__) == 'function') CBPhanloai_update_autofills__RAND__();
			});

			if(!$j("#CBPhanloai-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_CBPhanloai__RAND__.value, t: 'BL3', f: 'CBPhanloai' },
					success: function(resp) {
						$j('[name="CBPhanloai"]').val(resp.results[0].id);
						$j('[id=CBPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CBPhanloai-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

						if(typeof(CBPhanloai_update_autofills__RAND__) == 'function') CBPhanloai_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_CBPhanloai__RAND__.value, t: 'BL3', f: 'CBPhanloai' },
				success: function(resp) {
					$j('[id=CBPhanloai-container__RAND__], [id=CBPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CBPhanloai-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

					if(typeof(CBPhanloai_update_autofills__RAND__) == 'function') CBPhanloai_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function CHPhanloai_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#CHPhanloai-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_CHPhanloai__RAND__.value, t: 'BL3', f: 'CHPhanloai' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="CHPhanloai"]').val(resp.results[0].id);
							$j('[id=CHPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CHPhanloai-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


							if(typeof(CHPhanloai_update_autofills__RAND__) == 'function') CHPhanloai_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL3', f: 'CHPhanloai' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_CHPhanloai__RAND__.value = e.added.id;
				AppGini.current_CHPhanloai__RAND__.text = e.added.text;
				$j('[name="CHPhanloai"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


				if(typeof(CHPhanloai_update_autofills__RAND__) == 'function') CHPhanloai_update_autofills__RAND__();
			});

			if(!$j("#CHPhanloai-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_CHPhanloai__RAND__.value, t: 'BL3', f: 'CHPhanloai' },
					success: function(resp) {
						$j('[name="CHPhanloai"]').val(resp.results[0].id);
						$j('[id=CHPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CHPhanloai-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

						if(typeof(CHPhanloai_update_autofills__RAND__) == 'function') CHPhanloai_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_CHPhanloai__RAND__.value, t: 'BL3', f: 'CHPhanloai' },
				success: function(resp) {
					$j('[id=CHPhanloai-container__RAND__], [id=CHPhanloai-container-readonly__RAND__]').html('<span class="match-text" id="CHPhanloai-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

					if(typeof(CHPhanloai_update_autofills__RAND__) == 'function') CHPhanloai_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Phanloai_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Phanloai-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Phanloai__RAND__.value, t: 'BL3', f: 'Phanloai' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Phanloai"]').val(resp.results[0].id);
							$j('[id=Phanloai-container-readonly__RAND__]').html('<span class="match-text" id="Phanloai-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


							if(typeof(Phanloai_update_autofills__RAND__) == 'function') Phanloai_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'BL3', f: 'Phanloai' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Phanloai__RAND__.value = e.added.id;
				AppGini.current_Phanloai__RAND__.text = e.added.text;
				$j('[name="Phanloai"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }


				if(typeof(Phanloai_update_autofills__RAND__) == 'function') Phanloai_update_autofills__RAND__();
			});

			if(!$j("#Phanloai-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Phanloai__RAND__.value, t: 'BL3', f: 'Phanloai' },
					success: function(resp) {
						$j('[name="Phanloai"]').val(resp.results[0].id);
						$j('[id=Phanloai-container-readonly__RAND__]').html('<span class="match-text" id="Phanloai-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

						if(typeof(Phanloai_update_autofills__RAND__) == 'function') Phanloai_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Phanloai__RAND__.value, t: 'BL3', f: 'Phanloai' },
				success: function(resp) {
					$j('[id=Phanloai-container__RAND__], [id=Phanloai-container-readonly__RAND__]').html('<span class="match-text" id="Phanloai-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=PhanLoai_CTV_view_parent]').hide(); } else { $j('.btn[id=PhanLoai_CTV_view_parent]').show(); }

					if(typeof(Phanloai_update_autofills__RAND__) == 'function') Phanloai_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/BL3_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/BL3_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'BL3 details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return BL3_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return BL3_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return BL3_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#IDCTV').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IDCTV_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Ngaydauki').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaydauki\">' + (jQuery('#Ngaydauki').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Ngaycuoiki').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaycuoiki\">' + (jQuery('#Ngaycuoiki').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CBPhanloai').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CBPhanloai_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#CHPhanloai').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CHPhanloai_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Phanloai').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Phanloai_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Nx_Dx').replaceWith('<div class=\"form-control-static\" id=\"Nx_Dx\">' + (jQuery('#Nx_Dx').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaydauki').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaycuoiki').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(IDCTV)%%>', $combo_IDCTV->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(IDCTV)%%>', $combo_IDCTV->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(IDCTV)%%>', urlencode($combo_IDCTV->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(CBPhanloai)%%>', $combo_CBPhanloai->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CBPhanloai)%%>', $combo_CBPhanloai->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(CBPhanloai)%%>', urlencode($combo_CBPhanloai->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(CHPhanloai)%%>', $combo_CHPhanloai->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CHPhanloai)%%>', $combo_CHPhanloai->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(CHPhanloai)%%>', urlencode($combo_CHPhanloai->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Phanloai)%%>', $combo_Phanloai->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Phanloai)%%>', $combo_Phanloai->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Phanloai)%%>', urlencode($combo_Phanloai->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['IDCTV' => ['CTV', 'IDCTV'], 'CBPhanloai' => ['PhanLoai_CTV', 'CBPhanloai'], 'CHPhanloai' => ['PhanLoai_CTV', 'CHPhanloai'], 'Phanloai' => ['PhanLoai_CTV', 'Phanloai'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(IDBL3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(IDCTV)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaydauki)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaycuoiki)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CBPhanloai)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CHPhanloai)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Phanloai)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nx_Dx)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDBL3)%%>', safe_html($urow['IDBL3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDBL3)%%>', html_attr($row['IDBL3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL3)%%>', urlencode($urow['IDBL3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDCTV)%%>', safe_html($urow['IDCTV']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDCTV)%%>', html_attr($row['IDCTV']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDCTV)%%>', urlencode($urow['IDCTV']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaydauki)%%>', app_datetime($row['Ngaydauki'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaydauki)%%>', urlencode(app_datetime($urow['Ngaydauki'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaycuoiki)%%>', app_datetime($row['Ngaycuoiki'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaycuoiki)%%>', urlencode(app_datetime($urow['Ngaycuoiki'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CBPhanloai)%%>', safe_html($urow['CBPhanloai']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CBPhanloai)%%>', html_attr($row['CBPhanloai']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBPhanloai)%%>', urlencode($urow['CBPhanloai']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CHPhanloai)%%>', safe_html($urow['CHPhanloai']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CHPhanloai)%%>', html_attr($row['CHPhanloai']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CHPhanloai)%%>', urlencode($urow['CHPhanloai']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Phanloai)%%>', safe_html($urow['Phanloai']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Phanloai)%%>', html_attr($row['Phanloai']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Phanloai)%%>', urlencode($urow['Phanloai']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nx_Dx)%%>', safe_html($urow['Nx_Dx']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nx_Dx)%%>', html_attr($row['Nx_Dx']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nx_Dx)%%>', urlencode($urow['Nx_Dx']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(IDBL3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDBL3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(IDCTV)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDCTV)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaydauki)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaydauki)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaycuoiki)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaycuoiki)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CBPhanloai)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBPhanloai)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CHPhanloai)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CHPhanloai)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Phanloai)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Phanloai)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nx_Dx)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nx_Dx)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('BL3');
	if($selected_id) {
		$jdata = get_joined_record('BL3', $selected_id);
		if($jdata === false) $jdata = get_defaults('BL3');
		$rdata = $row;
	}
	$templateCode .= loadView('BL3-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: BL3_dv
	if(function_exists('BL3_dv')) {
		$args = [];
		BL3_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}