<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/CanBo.php');
	include_once(__DIR__ . '/CanBo_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('CanBo');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'CanBo';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`CanBo`.`IDCanbo`" => "IDCanbo",
		"`CanBo`.`IDMember`" => "IDMember",
		"`CanBo`.`Hovaten`" => "Hovaten",
		"`CanBo`.`Gioitinh`" => "Gioitinh",
		"`CanBo`.`Chucvu`" => "Chucvu",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* Donvi */" => "Donvi",
		"`CanBo`.`Thongtin`" => "Thongtin",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`CanBo`.`IDCanbo`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`DONVI1`.`Tendonvi`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`CanBo`.`IDCanbo`" => "IDCanbo",
		"`CanBo`.`IDMember`" => "IDMember",
		"`CanBo`.`Hovaten`" => "Hovaten",
		"`CanBo`.`Gioitinh`" => "Gioitinh",
		"`CanBo`.`Chucvu`" => "Chucvu",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* Donvi */" => "Donvi",
		"`CanBo`.`Thongtin`" => "Thongtin",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`CanBo`.`IDCanbo`" => "ID",
		"`CanBo`.`IDMember`" => "IDMember",
		"`CanBo`.`Hovaten`" => "Hovaten",
		"`CanBo`.`Gioitinh`" => "Gioitinh",
		"`CanBo`.`Chucvu`" => "Chucvu",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* Donvi */" => "Donvi",
		"`CanBo`.`Thongtin`" => "Thongtin",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`CanBo`.`IDCanbo`" => "IDCanbo",
		"`CanBo`.`IDMember`" => "IDMember",
		"`CanBo`.`Hovaten`" => "Hovaten",
		"`CanBo`.`Gioitinh`" => "Gioitinh",
		"`CanBo`.`Chucvu`" => "Chucvu",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* Donvi */" => "Donvi",
		"`CanBo`.`Thongtin`" => "Thongtin",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Donvi' => 'Donvi', ];

	$x->QueryFrom = "`CanBo` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`CanBo`.`Donvi` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'CanBo_view.php';
	$x->TableTitle = 'Canbo';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`CanBo`.`IDCanbo`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'IDMember', 'Hovaten', 'Gioitinh', 'Chucvu', 'Donvi', 'Thongtin', ];
	$x->ColFieldName = ['IDCanbo', 'IDMember', 'Hovaten', 'Gioitinh', 'Chucvu', 'Donvi', 'Thongtin', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/CanBo_templateTV.html';
	$x->SelectedTemplate = 'templates/CanBo_templateTVS.html';
	$x->TemplateDV = 'templates/CanBo_templateDV.html';
	$x->TemplateDVP = 'templates/CanBo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: CanBo_init
	$render = true;
	if(function_exists('CanBo_init')) {
		$args = [];
		$render = CanBo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: CanBo_header
	$headerCode = '';
	if(function_exists('CanBo_header')) {
		$args = [];
		$headerCode = CanBo_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: CanBo_footer
	$footerCode = '';
	if(function_exists('CanBo_footer')) {
		$args = [];
		$footerCode = CanBo_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
