<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/CTV.php');
	include_once(__DIR__ . '/CTV_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('CTV');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'CTV';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`CTV`.`IDCTV`" => "IDCTV",
		"`CTV`.`Sodangky`" => "Sodangky",
		"DATE_FORMAT(`CTV`.`Ngaydangky`, '%d/%m/%Y')" => "Ngaydangky",
		"IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') /* LoaiCTV */" => "LoaiCTV",
		"`CTV`.`Bidanh`" => "Bidanh",
		"DATE_FORMAT(`CTV`.`NgayPLgannhat`, '%d/%m/%Y')" => "NgayPLgannhat",
		"DATE_FORMAT(`CTV`.`NgaydenhanPL`, '%d/%m/%Y')" => "NgaydenhanPL",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVSD */" => "DVSD",
		"IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') /* CBSD */" => "CBSD",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') /* CBLap */" => "CBLap",
		"`CTV`.`Status`" => "Status",
		"`CTV`.`Diaban`" => "Diaban",
		"`CTV`.`Doituong`" => "Doituong",
		"`CTV`.`Vitri`" => "Vitri",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`CTV`.`IDCTV`',
		2 => 2,
		3 => '`CTV`.`Ngaydangky`',
		4 => '`LoaiCTV1`.`Ten`',
		5 => 5,
		6 => '`CTV`.`NgayPLgannhat`',
		7 => '`CTV`.`NgaydenhanPL`',
		8 => '`DONVI1`.`Tendonvi`',
		9 => '`CanBo1`.`Hovaten`',
		10 => '`DONVI2`.`Tendonvi`',
		11 => '`CanBo2`.`Hovaten`',
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`CTV`.`IDCTV`" => "IDCTV",
		"`CTV`.`Sodangky`" => "Sodangky",
		"DATE_FORMAT(`CTV`.`Ngaydangky`, '%d/%m/%Y')" => "Ngaydangky",
		"IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') /* LoaiCTV */" => "LoaiCTV",
		"`CTV`.`Bidanh`" => "Bidanh",
		"DATE_FORMAT(`CTV`.`NgayPLgannhat`, '%d/%m/%Y')" => "NgayPLgannhat",
		"DATE_FORMAT(`CTV`.`NgaydenhanPL`, '%d/%m/%Y')" => "NgaydenhanPL",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVSD */" => "DVSD",
		"IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') /* CBSD */" => "CBSD",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') /* CBLap */" => "CBLap",
		"`CTV`.`Status`" => "Status",
		"`CTV`.`Diaban`" => "Diaban",
		"`CTV`.`Doituong`" => "Doituong",
		"`CTV`.`Vitri`" => "Vitri",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`CTV`.`IDCTV`" => "ID",
		"`CTV`.`Sodangky`" => "Sodangky",
		"`CTV`.`Ngaydangky`" => "Ngaydangky",
		"IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') /* LoaiCTV */" => "LoaiCTV",
		"`CTV`.`Bidanh`" => "Bidanh",
		"`CTV`.`NgayPLgannhat`" => "NgayPhanloai",
		"`CTV`.`NgaydenhanPL`" => "NgaydenhanPL",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVSD */" => "DVSD",
		"IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') /* CBSD */" => "CBSD",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') /* CBLap */" => "CBLap",
		"`CTV`.`Status`" => "Status",
		"`CTV`.`Diaban`" => "Diaban",
		"`CTV`.`Doituong`" => "Doituong",
		"`CTV`.`Vitri`" => "Vitri",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`CTV`.`IDCTV`" => "IDCTV",
		"`CTV`.`Sodangky`" => "Sodangky",
		"DATE_FORMAT(`CTV`.`Ngaydangky`, '%d/%m/%Y')" => "Ngaydangky",
		"IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') /* LoaiCTV */" => "LoaiCTV",
		"`CTV`.`Bidanh`" => "Bidanh",
		"DATE_FORMAT(`CTV`.`NgayPLgannhat`, '%d/%m/%Y')" => "NgayPLgannhat",
		"DATE_FORMAT(`CTV`.`NgaydenhanPL`, '%d/%m/%Y')" => "NgaydenhanPL",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVSD */" => "DVSD",
		"IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') /* CBSD */" => "CBSD",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') /* CBLap */" => "CBLap",
		"`CTV`.`Status`" => "Status",
		"`CTV`.`Diaban`" => "Diaban",
		"`CTV`.`Doituong`" => "Doituong",
		"`CTV`.`Vitri`" => "Vitri",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['LoaiCTV' => 'LoaiCTV', 'DVSD' => 'DVSD', 'CBSD' => 'CBSD', 'DVLap' => 'DVLap', 'CBLap' => 'CBLap', ];

	$x->QueryFrom = "`CTV` LEFT JOIN `LoaiCTV` as LoaiCTV1 ON `LoaiCTV1`.`IDLoaiCTV`=`CTV`.`LoaiCTV` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`CTV`.`DVSD` LEFT JOIN `CanBo` as CanBo1 ON `CanBo1`.`IDCanbo`=`CTV`.`CBSD` LEFT JOIN `DONVI` as DONVI2 ON `DONVI2`.`IDDonvi`=`CTV`.`DVLap` LEFT JOIN `CanBo` as CanBo2 ON `CanBo2`.`IDCanbo`=`CTV`.`CBLap` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'CTV_view.php';
	$x->TableTitle = 'CTV';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`CTV`.`IDCTV`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Sodangky', 'Ngaydangky', 'LoaiCTV', 'Bidanh', 'NgayPhanloai', 'NgaydenhanPL', 'DVSD', 'CBSD', 'DVLap', 'CBLap', 'Status', 'Diaban', 'Doituong', 'Vitri', ];
	$x->ColFieldName = ['IDCTV', 'Sodangky', 'Ngaydangky', 'LoaiCTV', 'Bidanh', 'NgayPLgannhat', 'NgaydenhanPL', 'DVSD', 'CBSD', 'DVLap', 'CBLap', 'Status', 'Diaban', 'Doituong', 'Vitri', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/CTV_templateTV.html';
	$x->SelectedTemplate = 'templates/CTV_templateTVS.html';
	$x->TemplateDV = 'templates/CTV_templateDV.html';
	$x->TemplateDVP = 'templates/CTV_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: CTV_init
	$render = true;
	if(function_exists('CTV_init')) {
		$args = [];
		$render = CTV_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: CTV_header
	$headerCode = '';
	if(function_exists('CTV_header')) {
		$args = [];
		$headerCode = CTV_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: CTV_footer
	$footerCode = '';
	if(function_exists('CTV_footer')) {
		$args = [];
		$footerCode = CTV_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
