<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/DOITUONG.php');
	include_once(__DIR__ . '/DOITUONG_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('DOITUONG');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'DOITUONG';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`DOITUONG`.`IDDoituong`" => "IDDoituong",
		"`DOITUONG`.`Hovaten`" => "Hovaten",
		"DATE_FORMAT(`DOITUONG`.`Ngaysinh`, '%d/%m/%Y')" => "Ngaysinh",
		"`DOITUONG`.`CCCD`" => "CCCD",
		"`DOITUONG`.`TATS`" => "TATS",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`DOITUONG`.`IDDoituong`',
		2 => 2,
		3 => '`DOITUONG`.`Ngaysinh`',
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`DOITUONG`.`IDDoituong`" => "IDDoituong",
		"`DOITUONG`.`Hovaten`" => "Hovaten",
		"DATE_FORMAT(`DOITUONG`.`Ngaysinh`, '%d/%m/%Y')" => "Ngaysinh",
		"`DOITUONG`.`CCCD`" => "CCCD",
		"`DOITUONG`.`TATS`" => "TATS",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`DOITUONG`.`IDDoituong`" => "ID",
		"`DOITUONG`.`Hovaten`" => "Hovaten",
		"`DOITUONG`.`Ngaysinh`" => "Ngaysinh",
		"`DOITUONG`.`CCCD`" => "CCCD",
		"`DOITUONG`.`TATS`" => "TATS",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`DOITUONG`.`IDDoituong`" => "IDDoituong",
		"`DOITUONG`.`Hovaten`" => "Hovaten",
		"DATE_FORMAT(`DOITUONG`.`Ngaysinh`, '%d/%m/%Y')" => "Ngaysinh",
		"`DOITUONG`.`CCCD`" => "CCCD",
		"`DOITUONG`.`TATS`" => "TATS",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`DOITUONG` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'DOITUONG_view.php';
	$x->TableTitle = 'DOITUONG';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`DOITUONG`.`IDDoituong`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Hovaten', 'Ngaysinh', 'CCCD', 'TATS', ];
	$x->ColFieldName = ['Hovaten', 'Ngaysinh', 'CCCD', 'TATS', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/DOITUONG_templateTV.html';
	$x->SelectedTemplate = 'templates/DOITUONG_templateTVS.html';
	$x->TemplateDV = 'templates/DOITUONG_templateDV.html';
	$x->TemplateDVP = 'templates/DOITUONG_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: DOITUONG_init
	$render = true;
	if(function_exists('DOITUONG_init')) {
		$args = [];
		$render = DOITUONG_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: DOITUONG_header
	$headerCode = '';
	if(function_exists('DOITUONG_header')) {
		$args = [];
		$headerCode = DOITUONG_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: DOITUONG_footer
	$footerCode = '';
	if(function_exists('DOITUONG_footer')) {
		$args = [];
		$footerCode = DOITUONG_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
