<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Ketqua.php');
	include_once(__DIR__ . '/Ketqua_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Ketqua');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Ketqua';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Ketqua`.`ID`" => "ID",
		"`Ketqua`.`Ketqua`" => "Ketqua",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Ketqua`.`ID`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Ketqua`.`ID`" => "ID",
		"`Ketqua`.`Ketqua`" => "Ketqua",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Ketqua`.`ID`" => "ID",
		"`Ketqua`.`Ketqua`" => "Ketqua",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Ketqua`.`ID`" => "ID",
		"`Ketqua`.`Ketqua`" => "Ketqua",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Ketqua` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Ketqua_view.php';
	$x->TableTitle = 'Ketqua';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Ketqua`.`ID`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Ketqua', ];
	$x->ColFieldName = ['Ketqua', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Ketqua_templateTV.html';
	$x->SelectedTemplate = 'templates/Ketqua_templateTVS.html';
	$x->TemplateDV = 'templates/Ketqua_templateDV.html';
	$x->TemplateDVP = 'templates/Ketqua_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Ketqua_init
	$render = true;
	if(function_exists('Ketqua_init')) {
		$args = [];
		$render = Ketqua_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Ketqua_header
	$headerCode = '';
	if(function_exists('Ketqua_header')) {
		$args = [];
		$headerCode = Ketqua_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Ketqua_footer
	$footerCode = '';
	if(function_exists('Ketqua_footer')) {
		$args = [];
		$footerCode = Ketqua_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
