<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = [
			'DONVI' => [
			],
			'CanBo' => [
			],
			'CTV' => [
				'DVSD' => [
					'parent-table' => 'DONVI',
					'parent-primary-key' => 'IDDonvi',
					'child-primary-key' => 'IDCTV',
					'child-primary-key-index' => 0,
					'tab-label' => 'CTV <span class="hidden child-label-CTV child-field-caption">(DVSD)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'ID', 1 => 'Sodangky', 2 => 'Ngaydangky', 3 => 'LoaiCTV', 4 => 'Bidanh', 5 => 'NgayPhanloai', 6 => 'NgaydenhanPL', 7 => 'DVSD', 8 => 'CBSD', 9 => 'DVLap', 10 => 'CBLap', 11 => 'Status', 12 => 'Diaban', 13 => 'Doituong', 14 => 'Vitri'],
					'display-field-names' => [0 => 'IDCTV', 1 => 'Sodangky', 2 => 'Ngaydangky', 3 => 'LoaiCTV', 4 => 'Bidanh', 5 => 'NgayPLgannhat', 6 => 'NgaydenhanPL', 7 => 'DVSD', 8 => 'CBSD', 9 => 'DVLap', 10 => 'CBLap', 11 => 'Status', 12 => 'Diaban', 13 => 'Doituong', 14 => 'Vitri'],
					'sortable-fields' => [0 => '`CTV`.`IDCTV`', 1 => 2, 2 => '`CTV`.`Ngaydangky`', 3 => '`LoaiCTV1`.`Ten`', 4 => 5, 5 => '`CTV`.`NgayPLgannhat`', 6 => '`CTV`.`NgaydenhanPL`', 7 => '`DONVI1`.`Tendonvi`', 8 => '`CanBo1`.`Hovaten`', 9 => '`DONVI2`.`Tendonvi`', 10 => '`CanBo2`.`Hovaten`', 11 => 12, 12 => 13, 13 => 14, 14 => 15],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-CTV',
					'template-printable' => 'children-CTV-printable',
					'query' => "SELECT `CTV`.`IDCTV` as 'IDCTV', `CTV`.`Sodangky` as 'Sodangky', DATE_FORMAT(`CTV`.`Ngaydangky`, '%d/%m/%Y') as 'Ngaydangky', IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') as 'LoaiCTV', `CTV`.`Bidanh` as 'Bidanh', DATE_FORMAT(`CTV`.`NgayPLgannhat`, '%d/%m/%Y') as 'NgayPLgannhat', DATE_FORMAT(`CTV`.`NgaydenhanPL`, '%d/%m/%Y') as 'NgaydenhanPL', IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') as 'DVSD', IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') as 'CBSD', IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') as 'DVLap', IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') as 'CBLap', `CTV`.`Status` as 'Status', `CTV`.`Diaban` as 'Diaban', `CTV`.`Doituong` as 'Doituong', `CTV`.`Vitri` as 'Vitri' FROM `CTV` LEFT JOIN `LoaiCTV` as LoaiCTV1 ON `LoaiCTV1`.`IDLoaiCTV`=`CTV`.`LoaiCTV` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`CTV`.`DVSD` LEFT JOIN `CanBo` as CanBo1 ON `CanBo1`.`IDCanbo`=`CTV`.`CBSD` LEFT JOIN `DONVI` as DONVI2 ON `DONVI2`.`IDDonvi`=`CTV`.`DVLap` LEFT JOIN `CanBo` as CanBo2 ON `CanBo2`.`IDCanbo`=`CTV`.`CBLap` "
				],
				'DVLap' => [
					'parent-table' => 'DONVI',
					'parent-primary-key' => 'IDDonvi',
					'child-primary-key' => 'IDCTV',
					'child-primary-key-index' => 0,
					'tab-label' => 'CTV <span class="hidden child-label-CTV child-field-caption">(DVLap)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'ID', 1 => 'Sodangky', 2 => 'Ngaydangky', 3 => 'LoaiCTV', 4 => 'Bidanh', 5 => 'NgayPhanloai', 6 => 'NgaydenhanPL', 7 => 'DVSD', 8 => 'CBSD', 9 => 'DVLap', 10 => 'CBLap', 11 => 'Status', 12 => 'Diaban', 13 => 'Doituong', 14 => 'Vitri'],
					'display-field-names' => [0 => 'IDCTV', 1 => 'Sodangky', 2 => 'Ngaydangky', 3 => 'LoaiCTV', 4 => 'Bidanh', 5 => 'NgayPLgannhat', 6 => 'NgaydenhanPL', 7 => 'DVSD', 8 => 'CBSD', 9 => 'DVLap', 10 => 'CBLap', 11 => 'Status', 12 => 'Diaban', 13 => 'Doituong', 14 => 'Vitri'],
					'sortable-fields' => [0 => '`CTV`.`IDCTV`', 1 => 2, 2 => '`CTV`.`Ngaydangky`', 3 => '`LoaiCTV1`.`Ten`', 4 => 5, 5 => '`CTV`.`NgayPLgannhat`', 6 => '`CTV`.`NgaydenhanPL`', 7 => '`DONVI1`.`Tendonvi`', 8 => '`CanBo1`.`Hovaten`', 9 => '`DONVI2`.`Tendonvi`', 10 => '`CanBo2`.`Hovaten`', 11 => 12, 12 => 13, 13 => 14, 14 => 15],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-CTV',
					'template-printable' => 'children-CTV-printable',
					'query' => "SELECT `CTV`.`IDCTV` as 'IDCTV', `CTV`.`Sodangky` as 'Sodangky', DATE_FORMAT(`CTV`.`Ngaydangky`, '%d/%m/%Y') as 'Ngaydangky', IF(    CHAR_LENGTH(`LoaiCTV1`.`Ten`), CONCAT_WS('',   `LoaiCTV1`.`Ten`), '') as 'LoaiCTV', `CTV`.`Bidanh` as 'Bidanh', DATE_FORMAT(`CTV`.`NgayPLgannhat`, '%d/%m/%Y') as 'NgayPLgannhat', DATE_FORMAT(`CTV`.`NgaydenhanPL`, '%d/%m/%Y') as 'NgaydenhanPL', IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') as 'DVSD', IF(    CHAR_LENGTH(`CanBo1`.`Hovaten`), CONCAT_WS('',   `CanBo1`.`Hovaten`), '') as 'CBSD', IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') as 'DVLap', IF(    CHAR_LENGTH(`CanBo2`.`Hovaten`), CONCAT_WS('',   `CanBo2`.`Hovaten`), '') as 'CBLap', `CTV`.`Status` as 'Status', `CTV`.`Diaban` as 'Diaban', `CTV`.`Doituong` as 'Doituong', `CTV`.`Vitri` as 'Vitri' FROM `CTV` LEFT JOIN `LoaiCTV` as LoaiCTV1 ON `LoaiCTV1`.`IDLoaiCTV`=`CTV`.`LoaiCTV` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`CTV`.`DVSD` LEFT JOIN `CanBo` as CanBo1 ON `CanBo1`.`IDCanbo`=`CTV`.`CBSD` LEFT JOIN `DONVI` as DONVI2 ON `DONVI2`.`IDDonvi`=`CTV`.`DVLap` LEFT JOIN `CanBo` as CanBo2 ON `CanBo2`.`IDCanbo`=`CTV`.`CBLap` "
				],
			],
			'LoaiCTV' => [
			],
			'BL3' => [
				'IDCTV' => [
					'parent-table' => 'CTV',
					'parent-primary-key' => 'IDCTV',
					'child-primary-key' => 'IDBL3',
					'child-primary-key-index' => 0,
					'tab-label' => 'BL3 <span class="hidden child-label-BL3 child-field-caption">(IDCTV)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'ID', 1 => 'IDCTV', 2 => 'Ngaydauki', 3 => 'Ngaycuoiki', 4 => 'CBPhanloai', 5 => 'CHPhanloai', 6 => 'Phanloai', 7 => 'Nx Dx'],
					'display-field-names' => [0 => 'IDBL3', 1 => 'IDCTV', 2 => 'Ngaydauki', 3 => 'Ngaycuoiki', 4 => 'CBPhanloai', 5 => 'CHPhanloai', 6 => 'Phanloai', 7 => 'Nx_Dx'],
					'sortable-fields' => [0 => '`BL3`.`IDBL3`', 1 => '`CTV1`.`Bidanh`', 2 => '`BL3`.`Ngaydauki`', 3 => '`BL3`.`Ngaycuoiki`', 4 => '`PhanLoai_CTV1`.`Phanloai`', 5 => '`PhanLoai_CTV2`.`Phanloai`', 6 => '`PhanLoai_CTV3`.`Phanloai`', 7 => 8],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-BL3',
					'template-printable' => 'children-BL3-printable',
					'query' => "SELECT `BL3`.`IDBL3` as 'IDBL3', IF(    CHAR_LENGTH(`CTV1`.`Bidanh`), CONCAT_WS('',   `CTV1`.`Bidanh`), '') as 'IDCTV', DATE_FORMAT(`BL3`.`Ngaydauki`, '%d/%m/%Y') as 'Ngaydauki', DATE_FORMAT(`BL3`.`Ngaycuoiki`, '%d/%m/%Y') as 'Ngaycuoiki', IF(    CHAR_LENGTH(`PhanLoai_CTV1`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV1`.`Phanloai`), '') as 'CBPhanloai', IF(    CHAR_LENGTH(`PhanLoai_CTV2`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV2`.`Phanloai`), '') as 'CHPhanloai', IF(    CHAR_LENGTH(`PhanLoai_CTV3`.`Phanloai`), CONCAT_WS('',   `PhanLoai_CTV3`.`Phanloai`), '') as 'Phanloai', `BL3`.`Nx_Dx` as 'Nx_Dx' FROM `BL3` LEFT JOIN `CTV` as CTV1 ON `CTV1`.`IDCTV`=`BL3`.`IDCTV` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV1 ON `PhanLoai_CTV1`.`ID`=`BL3`.`CBPhanloai` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV2 ON `PhanLoai_CTV2`.`ID`=`BL3`.`CHPhanloai` LEFT JOIN `PhanLoai_CTV` as PhanLoai_CTV3 ON `PhanLoai_CTV3`.`ID`=`BL3`.`Phanloai` "
				],
			],
			'PhanLoai_CTV' => [
			],
			'BL2' => [
				'IDBL3' => [
					'parent-table' => 'BL3',
					'parent-primary-key' => 'IDBL3',
					'child-primary-key' => 'IDBL2',
					'child-primary-key-index' => 0,
					'tab-label' => 'BL2 <span class="hidden child-label-BL2 child-field-caption">(IDBL3)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'IDBL2', 1 => 'IDBL3', 2 => 'Ngaysinhhoat', 3 => 'Ngaybaotin', 4 => 'Tinbao', 5 => 'Xylytin', 6 => 'Ketqua'],
					'display-field-names' => [0 => 'IDBL2', 1 => 'IDBL3', 2 => 'Ngaysinhhoat', 3 => 'Ngaybaotin', 4 => 'Tinbao', 5 => 'Xylytin', 6 => 'Ketqua'],
					'sortable-fields' => [0 => '`BL2`.`IDBL2`', 1 => 2, 2 => '`BL2`.`Ngaysinhhoat`', 3 => '`BL2`.`Ngaybaotin`', 4 => '`TinBao1`.`TenTinbao`', 5 => '`XulyTin1`.`Xulytin`', 6 => '`Ketqua1`.`Ketqua`'],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-BL2',
					'template-printable' => 'children-BL2-printable',
					'query' => "SELECT `BL2`.`IDBL2` as 'IDBL2', IF(    CHAR_LENGTH(if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),'')) || CHAR_LENGTH(if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), CONCAT_WS('',   if(`BL31`.`Ngaydauki`,date_format(`BL31`.`Ngaydauki`,'%d/%m/%Y %H:%i'),''), '-', if(`BL31`.`Ngaycuoiki`,date_format(`BL31`.`Ngaycuoiki`,'%d/%m/%Y %H:%i'),'')), '') as 'IDBL3', DATE_FORMAT(`BL2`.`Ngaysinhhoat`, '%d/%m/%Y') as 'Ngaysinhhoat', DATE_FORMAT(`BL2`.`Ngaybaotin`, '%d/%m/%Y') as 'Ngaybaotin', IF(    CHAR_LENGTH(`TinBao1`.`TenTinbao`), CONCAT_WS('',   `TinBao1`.`TenTinbao`), '') as 'Tinbao', IF(    CHAR_LENGTH(`XulyTin1`.`Xulytin`), CONCAT_WS('',   `XulyTin1`.`Xulytin`), '') as 'Xylytin', IF(    CHAR_LENGTH(`Ketqua1`.`Ketqua`), CONCAT_WS('',   `Ketqua1`.`Ketqua`), '') as 'Ketqua' FROM `BL2` LEFT JOIN `BL3` as BL31 ON `BL31`.`IDBL3`=`BL2`.`IDBL3` LEFT JOIN `TinBao` as TinBao1 ON `TinBao1`.`ID`=`BL2`.`Tinbao` LEFT JOIN `XulyTin` as XulyTin1 ON `XulyTin1`.`ID`=`BL2`.`Xylytin` LEFT JOIN `Ketqua` as Ketqua1 ON `Ketqua1`.`ID`=`BL2`.`Ketqua` "
				],
			],
			'XulyTin' => [
			],
			'TinBao' => [
			],
			'Ketqua' => [
			],
			'STCN' => [
				'Doituong' => [
					'parent-table' => 'DOITUONG',
					'parent-primary-key' => 'IDDoituong',
					'child-primary-key' => 'IDSTCN',
					'child-primary-key-index' => 0,
					'tab-label' => 'STCN <span class="hidden child-label-STCN child-field-caption">(Doituong)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'ID', 1 => 'Sodangki', 2 => 'Ngaydangki', 3 => 'Ngaylap', 4 => 'CBLap', 5 => 'DVLap', 6 => 'CBQuanly', 7 => 'DVQuanly', 8 => 'Doituong', 9 => 'Status'],
					'display-field-names' => [0 => 'IDSTCN', 1 => 'Sodangki', 2 => 'Ngaydangki', 3 => 'Ngaylap', 4 => 'CBLap', 5 => 'DVLap', 6 => 'CBQuanly', 7 => 'DVQuanly', 8 => 'Doituong', 9 => 'Status'],
					'sortable-fields' => [0 => '`STCN`.`IDSTCN`', 1 => 2, 2 => '`STCN`.`Ngaydangki`', 3 => '`STCN`.`Ngaylap`', 4 => 5, 5 => '`DONVI1`.`Tendonvi`', 6 => 7, 7 => '`DONVI2`.`Tendonvi`', 8 => '`DOITUONG1`.`Hovaten`', 9 => 10],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-STCN',
					'template-printable' => 'children-STCN-printable',
					'query' => "SELECT `STCN`.`IDSTCN` as 'IDSTCN', `STCN`.`Sodangki` as 'Sodangki', DATE_FORMAT(`STCN`.`Ngaydangki`, '%d/%m/%Y') as 'Ngaydangki', DATE_FORMAT(`STCN`.`Ngaylap`, '%d/%m/%Y') as 'Ngaylap', `STCN`.`CBLap` as 'CBLap', IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') as 'DVLap', `STCN`.`CBQuanly` as 'CBQuanly', IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') as 'DVQuanly', IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') as 'Doituong', `STCN`.`Status` as 'Status' FROM `STCN` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`STCN`.`DVLap` LEFT JOIN `DONVI` as DONVI2 ON `DONVI2`.`IDDonvi`=`STCN`.`DVQuanly` LEFT JOIN `DOITUONG` as DOITUONG1 ON `DOITUONG1`.`IDDoituong`=`STCN`.`Doituong` "
				],
			],
			'STCNSTT' => [
				'IDSTCN' => [
					'parent-table' => 'STCN',
					'parent-primary-key' => 'IDSTCN',
					'child-primary-key' => 'IDSTT',
					'child-primary-key-index' => 0,
					'tab-label' => 'STCNSTT <span class="hidden child-label-STCNSTT child-field-caption">(IDSTCN)</span>',
					'auto-close' => true,
					'table-icon' => 'table.gif',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Phanloai', 2 => 'Danhmuc', 3 => 'Heloai', 4 => 'IDSTCN'],
					'display-field-names' => [1 => 'Phanloai', 2 => 'Danhmuc', 3 => 'Heloai', 4 => 'IDSTCN'],
					'sortable-fields' => [0 => '`STCNSTT`.`IDSTT`', 1 => 2, 2 => 3, 3 => 4, 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-STCNSTT',
					'template-printable' => 'children-STCNSTT-printable',
					'query' => "SELECT `STCNSTT`.`IDSTT` as 'IDSTT', `STCNSTT`.`Phanloai` as 'Phanloai', `STCNSTT`.`Danhmuc` as 'Danhmuc', `STCNSTT`.`Heloai` as 'Heloai', IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') as 'IDSTCN' FROM `STCNSTT` LEFT JOIN `STCN` as STCN1 ON `STCN1`.`IDSTCN`=`STCNSTT`.`IDSTCN` LEFT JOIN `DOITUONG` as DOITUONG1 ON `DOITUONG1`.`IDDoituong`=`STCN1`.`Doituong` "
				],
			],
			'DOITUONG' => [
			],
		];

	/*************************************/
	/* End of configuration */


	include_once(__DIR__ . '/lib.php');
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = [];
	foreach($pcConfig as $pcChildTable => $ChildrenLookups) {
		$permChild = getTablePermissions($pcChildTable);
		if(!$permChild['view']) continue;

		foreach($ChildrenLookups as $ChildLookupField => $ChildConfig) {
			$permParent = getTablePermissions($ChildConfig['parent-table']);
			if(!$permParent['view']) continue;

			$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
			// show add new only if configured above AND the user has insert permission
			$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = ($permChild['insert'] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']);
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = Request::val('ParentTable'); // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = Request::val('ChildTable');
		if(!in_array($ChildTable, array_keys($userPCConfig))) {
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable) { die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags(Request::val('SelectedID'));
	$ChildLookupField = Request::val('ChildLookupField');
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))) {
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}

	if(function_exists('child_records_config')) {
		// $userPCConfig is passed by reference
		child_records_config($ChildTable, $ChildLookupField, $userPCConfig);
	}

	$currentConfig = $userPCConfig[$ChildTable][$ChildLookupField];
	if(empty($currentConfig))
		die('<!-- No tables accessible to current user -->');

	$Page = intval(Request::val('Page'));
		if($Page < 1) $Page = 1;
	$SortBy = (Request::val('SortBy') != '' ? abs(intval(Request::val('SortBy'))) : false);
		if(!in_array($SortBy, array_keys($currentConfig['sortable-fields']), true))
			$SortBy = $currentConfig['default-sort-by'];
	$SortDirection = strtolower(Request::val('SortDirection'));
		if(!in_array($SortDirection, ['asc', 'desc']))
			$SortDirection = $currentConfig['default-sort-direction'];
	$Operation = strtolower(Request::val('Operation'));
		if(!in_array($Operation, ['get-records', 'show-children', 'get-records-printable', 'show-children-printable']))
			$Operation = 'get-records';

	/* process requested operation */
	switch($Operation) {
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups) {
				foreach($childLookups as $ChildLookupField => $childConfig) {
					if($childConfig['parent-table'] != $ParentTable) continue;

					$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\">" : '');

					$tabLabels .= "<li class=\"child-tab-label child-table-{$ChildTable} lookup-field-{$ChildLookupField} " . ($tabLabels ? '' : 'active') . "\">" .
							"<a href=\"#panel_{$ChildTable}-{$ChildLookupField}\" id=\"tab_{$ChildTable}-{$ChildLookupField}\" data-toggle=\"tab\">" .
								$TableIcon . $childConfig['tab-label'] .
								"<span class=\"badge child-count child-count-{$ChildTable}-{$ChildLookupField}\"></span>" .
							"</a>" .
						"</li>\n\t\t\t\t";

					$tabPanels .= "<div id=\"panel_{$ChildTable}-{$ChildLookupField}\" class=\"tab-pane" . ($tabPanels ? '' : ' active') . "\">" .
							"<i class=\"glyphicon glyphicon-refresh loop-rotate\"></i> " .
							"{$Translation['Loading ...']}" .
						"</div>\n\t\t\t\t";

					$tabLoaders .= "post('parent-children.php', " . json_encode([
							'ChildTable' => $ChildTable,
							'ChildLookupField' => $ChildLookupField,
							'SelectedID' => $SelectedID,
							'Page' => 1,
							'SortBy' => '',
							'SortDirection' => '',
							'Operation' => 'get-records'
						]) . ", 'panel_{$ChildTable}-{$ChildLookupField}');\n\t\t\t\t";
				}
			}

			if(!$tabLabels) { die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function() {
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded) {
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>

					/* show child field caption on tab title in case the same child table appears more than once */
					$j('.child-field-caption').each(function() {
						var clss = $j(this).attr('class').split(/\s+/).reduce(function(rc, cc) {
							return (cc.match(/child-label-.*/) ? '.' + cc : rc);
						}, '');

						// if class occurs more than once, remove .hidden
						if($j(clss).length > 1) $j(clss).removeClass('hidden');
					})
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups) {
				foreach($childLookups as $ChildLookupField => $childConfig) {
					if($childConfig['parent-table'] != $ParentTable) continue;

					$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\">" : '');

					$tabLabels .= "<button type=\"button\" class=\"btn btn-default child-tab-print-toggler\" data-target=\"#panel_{$ChildTable}-{$ChildLookupField}\" id=\"tab_{$ChildTable}-{$ChildLookupField}\" data-toggle=\"collapse\">" .
							"{$TableIcon} {$childConfig['tab-label']}" .
							"<span class=\"badge child-count child-count-{$ChildTable}-{$ChildLookupField}\"></span>" .
						"</button>\n\t\t\t\t\t";

					$tabPanels .= "<div id=\"panel_{$ChildTable}-{$ChildLookupField}\" class=\"collapse child-panel-print\">" .
							"<i class=\"glyphicon glyphicon-refresh loop-rotate\"></i> " .
							$Translation['Loading ...'] .
						"</div>\n\t\t\t\t";

					$tabLoaders .= "post('parent-children.php', " . json_encode([
							'ChildTable' => $ChildTable,
							'ChildLookupField' => $ChildLookupField,
							'SelectedID' => $SelectedID,
							'Page' => 1,
							'SortBy' => '',
							'SortDirection' => '',
							'Operation' => 'get-records-printable'
						]) . ", 'panel_{$ChildTable}-{$ChildLookupField}');\n\t\t\t\t";
				}
			}

			if(!$tabLabels) { die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function() {
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded) {
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable') {
				$currentConfig['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild['view'] == 1) { // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$currentConfig['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
			} elseif($permChild['view'] == 2) { // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$currentConfig['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
			} elseif($permChild['view'] == 3) { // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $currentConfig['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $currentConfig['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $currentConfig['records-per-page']);
			if($Page > $maxPage) { $Page = $maxPage; }

			// initiate output data array
			$data = [
				'config' => $currentConfig,
				'parameters' => [
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation,
				],
				'records' => [],
				'totalMatches' => $totalMatches
			];

			// build the data query
			if($totalMatches) { // if we have at least one record, proceed with fetching data
				$startRecord = $currentConfig['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$currentConfig['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $currentConfig['sortable-fields'][$SortBy] ? " ORDER BY {$currentConfig['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$currentConfig['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)) {
					$data['records'][$row[$currentConfig['child-primary-key-index']]] = $row;
				}
			} else { // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable') {
				$response = loadView($currentConfig['template-printable'], $data);
			} else {
				$response = loadView($currentConfig['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
