<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/PhanLoai_CTV.php');
	include_once(__DIR__ . '/PhanLoai_CTV_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('PhanLoai_CTV');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'PhanLoai_CTV';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`PhanLoai_CTV`.`ID`" => "ID",
		"`PhanLoai_CTV`.`Phanloai`" => "Phanloai",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`PhanLoai_CTV`.`ID`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`PhanLoai_CTV`.`ID`" => "ID",
		"`PhanLoai_CTV`.`Phanloai`" => "Phanloai",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`PhanLoai_CTV`.`ID`" => "ID",
		"`PhanLoai_CTV`.`Phanloai`" => "Phanloai",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`PhanLoai_CTV`.`ID`" => "ID",
		"`PhanLoai_CTV`.`Phanloai`" => "Phanloai",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`PhanLoai_CTV` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'PhanLoai_CTV_view.php';
	$x->TableTitle = 'Phanloai CTV';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`PhanLoai_CTV`.`ID`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['ID', 'Phanloai', ];
	$x->ColFieldName = ['ID', 'Phanloai', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/PhanLoai_CTV_templateTV.html';
	$x->SelectedTemplate = 'templates/PhanLoai_CTV_templateTVS.html';
	$x->TemplateDV = 'templates/PhanLoai_CTV_templateDV.html';
	$x->TemplateDVP = 'templates/PhanLoai_CTV_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: PhanLoai_CTV_init
	$render = true;
	if(function_exists('PhanLoai_CTV_init')) {
		$args = [];
		$render = PhanLoai_CTV_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: PhanLoai_CTV_header
	$headerCode = '';
	if(function_exists('PhanLoai_CTV_header')) {
		$args = [];
		$headerCode = PhanLoai_CTV_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: PhanLoai_CTV_footer
	$footerCode = '';
	if(function_exists('PhanLoai_CTV_footer')) {
		$args = [];
		$footerCode = PhanLoai_CTV_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
