<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/STCN.php');
	include_once(__DIR__ . '/STCN_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('STCN');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'STCN';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`STCN`.`IDSTCN`" => "IDSTCN",
		"`STCN`.`Sodangki`" => "Sodangki",
		"DATE_FORMAT(`STCN`.`Ngaydangki`, '%d/%m/%Y')" => "Ngaydangki",
		"DATE_FORMAT(`STCN`.`Ngaylap`, '%d/%m/%Y')" => "Ngaylap",
		"`STCN`.`CBLap`" => "CBLap",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"`STCN`.`CBQuanly`" => "CBQuanly",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVQuanly */" => "DVQuanly",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* Doituong */" => "Doituong",
		"`STCN`.`Status`" => "Status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`STCN`.`IDSTCN`',
		2 => 2,
		3 => '`STCN`.`Ngaydangki`',
		4 => '`STCN`.`Ngaylap`',
		5 => 5,
		6 => '`DONVI1`.`Tendonvi`',
		7 => 7,
		8 => '`DONVI2`.`Tendonvi`',
		9 => '`DOITUONG1`.`Hovaten`',
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`STCN`.`IDSTCN`" => "IDSTCN",
		"`STCN`.`Sodangki`" => "Sodangki",
		"DATE_FORMAT(`STCN`.`Ngaydangki`, '%d/%m/%Y')" => "Ngaydangki",
		"DATE_FORMAT(`STCN`.`Ngaylap`, '%d/%m/%Y')" => "Ngaylap",
		"`STCN`.`CBLap`" => "CBLap",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"`STCN`.`CBQuanly`" => "CBQuanly",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVQuanly */" => "DVQuanly",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* Doituong */" => "Doituong",
		"`STCN`.`Status`" => "Status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`STCN`.`IDSTCN`" => "ID",
		"`STCN`.`Sodangki`" => "Sodangki",
		"`STCN`.`Ngaydangki`" => "Ngaydangki",
		"`STCN`.`Ngaylap`" => "Ngaylap",
		"`STCN`.`CBLap`" => "CBLap",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"`STCN`.`CBQuanly`" => "CBQuanly",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVQuanly */" => "DVQuanly",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* Doituong */" => "Doituong",
		"`STCN`.`Status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`STCN`.`IDSTCN`" => "IDSTCN",
		"`STCN`.`Sodangki`" => "Sodangki",
		"DATE_FORMAT(`STCN`.`Ngaydangki`, '%d/%m/%Y')" => "Ngaydangki",
		"DATE_FORMAT(`STCN`.`Ngaylap`, '%d/%m/%Y')" => "Ngaylap",
		"`STCN`.`CBLap`" => "CBLap",
		"IF(    CHAR_LENGTH(`DONVI1`.`Tendonvi`), CONCAT_WS('',   `DONVI1`.`Tendonvi`), '') /* DVLap */" => "DVLap",
		"`STCN`.`CBQuanly`" => "CBQuanly",
		"IF(    CHAR_LENGTH(`DONVI2`.`Tendonvi`), CONCAT_WS('',   `DONVI2`.`Tendonvi`), '') /* DVQuanly */" => "DVQuanly",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* Doituong */" => "Doituong",
		"`STCN`.`Status`" => "Status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['DVLap' => 'DVLap', 'DVQuanly' => 'DVQuanly', 'Doituong' => 'Doituong', ];

	$x->QueryFrom = "`STCN` LEFT JOIN `DONVI` as DONVI1 ON `DONVI1`.`IDDonvi`=`STCN`.`DVLap` LEFT JOIN `DONVI` as DONVI2 ON `DONVI2`.`IDDonvi`=`STCN`.`DVQuanly` LEFT JOIN `DOITUONG` as DOITUONG1 ON `DOITUONG1`.`IDDoituong`=`STCN`.`Doituong` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'STCN_view.php';
	$x->TableTitle = 'STCN';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`STCN`.`IDSTCN`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Sodangki', 'Ngaydangki', 'Ngaylap', 'CBLap', 'DVLap', 'CBQuanly', 'DVQuanly', 'Doituong', 'Status', ];
	$x->ColFieldName = ['IDSTCN', 'Sodangki', 'Ngaydangki', 'Ngaylap', 'CBLap', 'DVLap', 'CBQuanly', 'DVQuanly', 'Doituong', 'Status', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/STCN_templateTV.html';
	$x->SelectedTemplate = 'templates/STCN_templateTVS.html';
	$x->TemplateDV = 'templates/STCN_templateDV.html';
	$x->TemplateDVP = 'templates/STCN_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: STCN_init
	$render = true;
	if(function_exists('STCN_init')) {
		$args = [];
		$render = STCN_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: STCN_header
	$headerCode = '';
	if(function_exists('STCN_header')) {
		$args = [];
		$headerCode = STCN_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: STCN_footer
	$footerCode = '';
	if(function_exists('STCN_footer')) {
		$args = [];
		$footerCode = STCN_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
