<?php

// Data functions (insert, update, delete, form) for table STCNSTT

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function STCNSTT_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('STCNSTT');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Phanloai' => Request::val('Phanloai', ''),
		'Danhmuc' => Request::val('Danhmuc', ''),
		'Heloai' => Request::val('Heloai', ''),
		'IDSTCN' => Request::lookup('IDSTCN', ''),
	];


	// hook: STCNSTT_before_insert
	if(function_exists('STCNSTT_before_insert')) {
		$args = [];
		if(!STCNSTT_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('STCNSTT', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('STCNSTT', $recID, calculated_fields()['STCNSTT']);

	// hook: STCNSTT_after_insert
	if(function_exists('STCNSTT_after_insert')) {
		$res = sql("SELECT * FROM `STCNSTT` WHERE `IDSTT`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!STCNSTT_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('STCNSTT', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) STCNSTT_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function STCNSTT_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function STCNSTT_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('STCNSTT', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: STCNSTT_before_delete
	if(function_exists('STCNSTT_before_delete')) {
		$args = [];
		if(!STCNSTT_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `STCNSTT` WHERE `IDSTT`='{$selected_id}'", $eo);

	// hook: STCNSTT_after_delete
	if(function_exists('STCNSTT_after_delete')) {
		$args = [];
		STCNSTT_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='STCNSTT' AND `pkValue`='{$selected_id}'", $eo);
}

function STCNSTT_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('STCNSTT', $selected_id, 'edit')) return false;

	$data = [
		'Phanloai' => Request::val('Phanloai', ''),
		'Danhmuc' => Request::val('Danhmuc', ''),
		'Heloai' => Request::val('Heloai', ''),
		'IDSTCN' => Request::lookup('IDSTCN', ''),
	];

	// get existing values
	$old_data = getRecord('STCNSTT', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: STCNSTT_before_update
	if(function_exists('STCNSTT_before_update')) {
		$args = ['old_data' => $old_data];
		if(!STCNSTT_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'STCNSTT', 
		backtick_keys_once($set), 
		['`IDSTT`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="STCNSTT_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('STCNSTT', $data['selectedID'], calculated_fields()['STCNSTT']);

	// hook: STCNSTT_after_update
	if(function_exists('STCNSTT_after_update')) {
		$res = sql("SELECT * FROM `STCNSTT` WHERE `IDSTT`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['IDSTT'];
		$args = ['old_data' => $old_data];
		if(!STCNSTT_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='STCNSTT' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function STCNSTT_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('STCNSTT');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_IDSTCN = Request::val('filterer_IDSTCN');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Phanloai
	$combo_Phanloai = new Combo;
	$combo_Phanloai->ListType = 0;
	$combo_Phanloai->MultipleSeparator = ', ';
	$combo_Phanloai->ListBoxHeight = 10;
	$combo_Phanloai->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/STCNSTT.Phanloai.csv')) {
		$Phanloai_data = addslashes(implode('', @file(__DIR__ . '/hooks/STCNSTT.Phanloai.csv')));
		$combo_Phanloai->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Phanloai_data))));
		$combo_Phanloai->ListData = $combo_Phanloai->ListItem;
	} else {
		$combo_Phanloai->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("A;;B"))));
		$combo_Phanloai->ListData = $combo_Phanloai->ListItem;
	}
	$combo_Phanloai->SelectName = 'Phanloai';
	// combobox: Danhmuc
	$combo_Danhmuc = new Combo;
	$combo_Danhmuc->ListType = 0;
	$combo_Danhmuc->MultipleSeparator = ', ';
	$combo_Danhmuc->ListBoxHeight = 10;
	$combo_Danhmuc->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/STCNSTT.Danhmuc.csv')) {
		$Danhmuc_data = addslashes(implode('', @file(__DIR__ . '/hooks/STCNSTT.Danhmuc.csv')));
		$combo_Danhmuc->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Danhmuc_data))));
		$combo_Danhmuc->ListData = $combo_Danhmuc->ListItem;
	} else {
		$combo_Danhmuc->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("I;;II;;III;;IV"))));
		$combo_Danhmuc->ListData = $combo_Danhmuc->ListItem;
	}
	$combo_Danhmuc->SelectName = 'Danhmuc';
	// combobox: Heloai
	$combo_Heloai = new Combo;
	$combo_Heloai->ListType = 0;
	$combo_Heloai->MultipleSeparator = ', ';
	$combo_Heloai->ListBoxHeight = 10;
	$combo_Heloai->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/STCNSTT.Heloai.csv')) {
		$Heloai_data = addslashes(implode('', @file(__DIR__ . '/hooks/STCNSTT.Heloai.csv')));
		$combo_Heloai->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Heloai_data))));
		$combo_Heloai->ListData = $combo_Heloai->ListItem;
	} else {
		$combo_Heloai->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("1;;2;;3;;4;;5;;6;;7;;8;;9;;10;;11;;12"))));
		$combo_Heloai->ListData = $combo_Heloai->ListItem;
	}
	$combo_Heloai->SelectName = 'Heloai';
	// combobox: IDSTCN
	$combo_IDSTCN = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('STCNSTT', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('STCNSTT', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('STCNSTT', $selected_id, 'delete');

		$res = sql("SELECT * FROM `STCNSTT` WHERE `IDSTT`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'STCNSTT_view.php', false);
		}
		$combo_Phanloai->SelectedData = $row['Phanloai'];
		$combo_Danhmuc->SelectedData = $row['Danhmuc'];
		$combo_Heloai->SelectedData = $row['Heloai'];
		$combo_IDSTCN->SelectedData = $row['IDSTCN'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Phanloai->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_Danhmuc->SelectedText = (isset($filterField[1]) && $filterField[1] == '3' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_Heloai->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_IDSTCN->SelectedData = $filterer_IDSTCN;
	}
	$combo_Phanloai->Render();
	$combo_Danhmuc->Render();
	$combo_Heloai->Render();
	$combo_IDSTCN->HTML = '<span id="IDSTCN-container' . $rnd1 . '"></span><input type="hidden" name="IDSTCN" id="IDSTCN' . $rnd1 . '" value="' . html_attr($combo_IDSTCN->SelectedData) . '">';
	$combo_IDSTCN->MatchText = '<span id="IDSTCN-container-readonly' . $rnd1 . '"></span><input type="hidden" name="IDSTCN" id="IDSTCN' . $rnd1 . '" value="' . html_attr($combo_IDSTCN->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_IDSTCN__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['IDSTCN'] : htmlspecialchars($filterer_IDSTCN, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(IDSTCN_reload__RAND__) == 'function') IDSTCN_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function IDSTCN_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#IDSTCN-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_IDSTCN__RAND__.value, t: 'STCNSTT', f: 'IDSTCN' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="IDSTCN"]').val(resp.results[0].id);
							$j('[id=IDSTCN-container-readonly__RAND__]').html('<span class="match-text" id="IDSTCN-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=STCN_view_parent]').hide(); } else { $j('.btn[id=STCN_view_parent]').show(); }


							if(typeof(IDSTCN_update_autofills__RAND__) == 'function') IDSTCN_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'STCNSTT', f: 'IDSTCN' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_IDSTCN__RAND__.value = e.added.id;
				AppGini.current_IDSTCN__RAND__.text = e.added.text;
				$j('[name="IDSTCN"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=STCN_view_parent]').hide(); } else { $j('.btn[id=STCN_view_parent]').show(); }


				if(typeof(IDSTCN_update_autofills__RAND__) == 'function') IDSTCN_update_autofills__RAND__();
			});

			if(!$j("#IDSTCN-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_IDSTCN__RAND__.value, t: 'STCNSTT', f: 'IDSTCN' },
					success: function(resp) {
						$j('[name="IDSTCN"]').val(resp.results[0].id);
						$j('[id=IDSTCN-container-readonly__RAND__]').html('<span class="match-text" id="IDSTCN-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=STCN_view_parent]').hide(); } else { $j('.btn[id=STCN_view_parent]').show(); }

						if(typeof(IDSTCN_update_autofills__RAND__) == 'function') IDSTCN_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_IDSTCN__RAND__.value, t: 'STCNSTT', f: 'IDSTCN' },
				success: function(resp) {
					$j('[id=IDSTCN-container__RAND__], [id=IDSTCN-container-readonly__RAND__]').html('<span class="match-text" id="IDSTCN-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=STCN_view_parent]').hide(); } else { $j('.btn[id=STCN_view_parent]').show(); }

					if(typeof(IDSTCN_update_autofills__RAND__) == 'function') IDSTCN_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/STCNSTT_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/STCNSTT_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'STCNSTT details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return STCNSTT_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return STCNSTT_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return STCNSTT_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Phanloai').replaceWith('<div class=\"form-control-static\" id=\"Phanloai\">' + (jQuery('#Phanloai').val() || '') + '</div>'); jQuery('#Phanloai-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Danhmuc').replaceWith('<div class=\"form-control-static\" id=\"Danhmuc\">' + (jQuery('#Danhmuc').val() || '') + '</div>'); jQuery('#Danhmuc-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Heloai').replaceWith('<div class=\"form-control-static\" id=\"Heloai\">' + (jQuery('#Heloai').val() || '') + '</div>'); jQuery('#Heloai-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#IDSTCN').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#IDSTCN_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Phanloai)%%>', $combo_Phanloai->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Phanloai)%%>', $combo_Phanloai->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Danhmuc)%%>', $combo_Danhmuc->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Danhmuc)%%>', $combo_Danhmuc->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Heloai)%%>', $combo_Heloai->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Heloai)%%>', $combo_Heloai->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(IDSTCN)%%>', $combo_IDSTCN->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(IDSTCN)%%>', $combo_IDSTCN->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(IDSTCN)%%>', urlencode($combo_IDSTCN->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['IDSTCN' => ['STCN', 'IDSTCN'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(IDSTT)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Phanloai)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Danhmuc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Heloai)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(IDSTCN)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDSTT)%%>', safe_html($urow['IDSTT']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDSTT)%%>', html_attr($row['IDSTT']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTT)%%>', urlencode($urow['IDSTT']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Phanloai)%%>', safe_html($urow['Phanloai']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Phanloai)%%>', html_attr($row['Phanloai']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Phanloai)%%>', urlencode($urow['Phanloai']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Danhmuc)%%>', safe_html($urow['Danhmuc']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Danhmuc)%%>', html_attr($row['Danhmuc']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Danhmuc)%%>', urlencode($urow['Danhmuc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Heloai)%%>', safe_html($urow['Heloai']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Heloai)%%>', html_attr($row['Heloai']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Heloai)%%>', urlencode($urow['Heloai']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDSTCN)%%>', safe_html($urow['IDSTCN']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDSTCN)%%>', html_attr($row['IDSTCN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTCN)%%>', urlencode($urow['IDSTCN']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(IDSTT)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTT)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Phanloai)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Phanloai)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Danhmuc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Danhmuc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Heloai)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Heloai)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(IDSTCN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTCN)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('STCNSTT');
	if($selected_id) {
		$jdata = get_joined_record('STCNSTT', $selected_id);
		if($jdata === false) $jdata = get_defaults('STCNSTT');
		$rdata = $row;
	}
	$templateCode .= loadView('STCNSTT-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: STCNSTT_dv
	if(function_exists('STCNSTT_dv')) {
		$args = [];
		STCNSTT_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}