<?php

// Data functions (insert, update, delete, form) for table STCN

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function STCN_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('STCN');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Sodangki' => Request::val('Sodangki', ''),
		'Ngaydangki' => mysql_datetime(Request::val('Ngaydangki', '')),
		'Ngaylap' => mysql_datetime(Request::val('Ngaylap', '')),
		'CBLap' => Request::val('CBLap', ''),
		'DVLap' => Request::lookup('DVLap', ''),
		'CBQuanly' => Request::val('CBQuanly', ''),
		'DVQuanly' => Request::lookup('DVQuanly', ''),
		'Doituong' => Request::lookup('Doituong', ''),
		'Status' => Request::val('Status', ''),
	];


	// hook: STCN_before_insert
	if(function_exists('STCN_before_insert')) {
		$args = [];
		if(!STCN_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('STCN', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('STCN', $recID, calculated_fields()['STCN']);

	// hook: STCN_after_insert
	if(function_exists('STCN_after_insert')) {
		$res = sql("SELECT * FROM `STCN` WHERE `IDSTCN`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!STCN_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('STCN', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) STCN_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function STCN_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// copy STCNSTT
	$res = sql("SELECT * FROM `STCNSTT` WHERE `IDSTCN`='{$safe_sid}'", $eo);
	while($row = db_fetch_assoc($res)) {
		$data = [
			'SelectedID' => $row['IDSTT'],
			'Phanloai' => $row['Phanloai'],
			'Danhmuc' => $row['Danhmuc'],
			'Heloai' => $row['Heloai'],
			'IDSTCN' => $destination_id,
		];

		$ch = curl_insert_handler('STCNSTT', $data);
		if($ch !== false) $requests[] = $ch;
	}

	// launch requests, asynchronously
	curl_batch($requests);
}

function STCN_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('STCN', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: STCN_before_delete
	if(function_exists('STCN_before_delete')) {
		$args = [];
		if(!STCN_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: STCNSTT
	$res = sql("SELECT `IDSTCN` FROM `STCN` WHERE `IDSTCN`='{$selected_id}'", $eo);
	$IDSTCN = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `STCNSTT` WHERE `IDSTCN`='" . makeSafe($IDSTCN[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'STCNSTT', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'STCNSTT', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'STCN_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'STCN_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `STCN` WHERE `IDSTCN`='{$selected_id}'", $eo);

	// hook: STCN_after_delete
	if(function_exists('STCN_after_delete')) {
		$args = [];
		STCN_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='STCN' AND `pkValue`='{$selected_id}'", $eo);
}

function STCN_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('STCN', $selected_id, 'edit')) return false;

	$data = [
		'Sodangki' => Request::val('Sodangki', ''),
		'Ngaydangki' => mysql_datetime(Request::val('Ngaydangki', '')),
		'Ngaylap' => mysql_datetime(Request::val('Ngaylap', '')),
		'CBLap' => Request::val('CBLap', ''),
		'DVLap' => Request::lookup('DVLap', ''),
		'CBQuanly' => Request::val('CBQuanly', ''),
		'DVQuanly' => Request::lookup('DVQuanly', ''),
		'Doituong' => Request::lookup('Doituong', ''),
		'Status' => Request::val('Status', ''),
	];

	// get existing values
	$old_data = getRecord('STCN', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: STCN_before_update
	if(function_exists('STCN_before_update')) {
		$args = ['old_data' => $old_data];
		if(!STCN_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'STCN', 
		backtick_keys_once($set), 
		['`IDSTCN`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="STCN_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('STCN', $data['selectedID'], calculated_fields()['STCN']);

	// hook: STCN_after_update
	if(function_exists('STCN_after_update')) {
		$res = sql("SELECT * FROM `STCN` WHERE `IDSTCN`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['IDSTCN'];
		$args = ['old_data' => $old_data];
		if(!STCN_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='STCN' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function STCN_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('STCN');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_DVLap = Request::val('filterer_DVLap');
	$filterer_DVQuanly = Request::val('filterer_DVQuanly');
	$filterer_Doituong = Request::val('filterer_Doituong');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: DVLap
	$combo_DVLap = new DataCombo;
	// combobox: DVQuanly
	$combo_DVQuanly = new DataCombo;
	// combobox: Doituong
	$combo_Doituong = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('STCN', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('STCN', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('STCN', $selected_id, 'delete');

		$res = sql("SELECT * FROM `STCN` WHERE `IDSTCN`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'STCN_view.php', false);
		}
		$combo_DVLap->SelectedData = $row['DVLap'];
		$combo_DVQuanly->SelectedData = $row['DVQuanly'];
		$combo_Doituong->SelectedData = $row['Doituong'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_DVLap->SelectedData = $filterer_DVLap;
		$combo_DVQuanly->SelectedData = $filterer_DVQuanly;
		$combo_Doituong->SelectedData = $filterer_Doituong;
	}
	$combo_DVLap->HTML = '<span id="DVLap-container' . $rnd1 . '"></span><input type="hidden" name="DVLap" id="DVLap' . $rnd1 . '" value="' . html_attr($combo_DVLap->SelectedData) . '">';
	$combo_DVLap->MatchText = '<span id="DVLap-container-readonly' . $rnd1 . '"></span><input type="hidden" name="DVLap" id="DVLap' . $rnd1 . '" value="' . html_attr($combo_DVLap->SelectedData) . '">';
	$combo_DVQuanly->HTML = '<span id="DVQuanly-container' . $rnd1 . '"></span><input type="hidden" name="DVQuanly" id="DVQuanly' . $rnd1 . '" value="' . html_attr($combo_DVQuanly->SelectedData) . '">';
	$combo_DVQuanly->MatchText = '<span id="DVQuanly-container-readonly' . $rnd1 . '"></span><input type="hidden" name="DVQuanly" id="DVQuanly' . $rnd1 . '" value="' . html_attr($combo_DVQuanly->SelectedData) . '">';
	$combo_Doituong->HTML = '<span id="Doituong-container' . $rnd1 . '"></span><input type="hidden" name="Doituong" id="Doituong' . $rnd1 . '" value="' . html_attr($combo_Doituong->SelectedData) . '">';
	$combo_Doituong->MatchText = '<span id="Doituong-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Doituong" id="Doituong' . $rnd1 . '" value="' . html_attr($combo_Doituong->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_DVLap__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['DVLap'] : htmlspecialchars($filterer_DVLap, ENT_QUOTES)); ?>"};
		AppGini.current_DVQuanly__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['DVQuanly'] : htmlspecialchars($filterer_DVQuanly, ENT_QUOTES)); ?>"};
		AppGini.current_Doituong__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Doituong'] : htmlspecialchars($filterer_Doituong, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(DVLap_reload__RAND__) == 'function') DVLap_reload__RAND__();
				if(typeof(DVQuanly_reload__RAND__) == 'function') DVQuanly_reload__RAND__();
				if(typeof(Doituong_reload__RAND__) == 'function') Doituong_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function DVLap_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#DVLap-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_DVLap__RAND__.value, t: 'STCN', f: 'DVLap' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="DVLap"]').val(resp.results[0].id);
							$j('[id=DVLap-container-readonly__RAND__]').html('<span class="match-text" id="DVLap-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }


							if(typeof(DVLap_update_autofills__RAND__) == 'function') DVLap_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'STCN', f: 'DVLap' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_DVLap__RAND__.value = e.added.id;
				AppGini.current_DVLap__RAND__.text = e.added.text;
				$j('[name="DVLap"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }


				if(typeof(DVLap_update_autofills__RAND__) == 'function') DVLap_update_autofills__RAND__();
			});

			if(!$j("#DVLap-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_DVLap__RAND__.value, t: 'STCN', f: 'DVLap' },
					success: function(resp) {
						$j('[name="DVLap"]').val(resp.results[0].id);
						$j('[id=DVLap-container-readonly__RAND__]').html('<span class="match-text" id="DVLap-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }

						if(typeof(DVLap_update_autofills__RAND__) == 'function') DVLap_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_DVLap__RAND__.value, t: 'STCN', f: 'DVLap' },
				success: function(resp) {
					$j('[id=DVLap-container__RAND__], [id=DVLap-container-readonly__RAND__]').html('<span class="match-text" id="DVLap-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }

					if(typeof(DVLap_update_autofills__RAND__) == 'function') DVLap_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function DVQuanly_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#DVQuanly-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_DVQuanly__RAND__.value, t: 'STCN', f: 'DVQuanly' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="DVQuanly"]').val(resp.results[0].id);
							$j('[id=DVQuanly-container-readonly__RAND__]').html('<span class="match-text" id="DVQuanly-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }


							if(typeof(DVQuanly_update_autofills__RAND__) == 'function') DVQuanly_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'STCN', f: 'DVQuanly' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_DVQuanly__RAND__.value = e.added.id;
				AppGini.current_DVQuanly__RAND__.text = e.added.text;
				$j('[name="DVQuanly"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }


				if(typeof(DVQuanly_update_autofills__RAND__) == 'function') DVQuanly_update_autofills__RAND__();
			});

			if(!$j("#DVQuanly-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_DVQuanly__RAND__.value, t: 'STCN', f: 'DVQuanly' },
					success: function(resp) {
						$j('[name="DVQuanly"]').val(resp.results[0].id);
						$j('[id=DVQuanly-container-readonly__RAND__]').html('<span class="match-text" id="DVQuanly-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }

						if(typeof(DVQuanly_update_autofills__RAND__) == 'function') DVQuanly_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_DVQuanly__RAND__.value, t: 'STCN', f: 'DVQuanly' },
				success: function(resp) {
					$j('[id=DVQuanly-container__RAND__], [id=DVQuanly-container-readonly__RAND__]').html('<span class="match-text" id="DVQuanly-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DONVI_view_parent]').hide(); } else { $j('.btn[id=DONVI_view_parent]').show(); }

					if(typeof(DVQuanly_update_autofills__RAND__) == 'function') DVQuanly_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Doituong_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Doituong-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Doituong__RAND__.value, t: 'STCN', f: 'Doituong' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Doituong"]').val(resp.results[0].id);
							$j('[id=Doituong-container-readonly__RAND__]').html('<span class="match-text" id="Doituong-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DOITUONG_view_parent]').hide(); } else { $j('.btn[id=DOITUONG_view_parent]').show(); }


							if(typeof(Doituong_update_autofills__RAND__) == 'function') Doituong_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'STCN', f: 'Doituong' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Doituong__RAND__.value = e.added.id;
				AppGini.current_Doituong__RAND__.text = e.added.text;
				$j('[name="Doituong"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DOITUONG_view_parent]').hide(); } else { $j('.btn[id=DOITUONG_view_parent]').show(); }


				if(typeof(Doituong_update_autofills__RAND__) == 'function') Doituong_update_autofills__RAND__();
			});

			if(!$j("#Doituong-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Doituong__RAND__.value, t: 'STCN', f: 'Doituong' },
					success: function(resp) {
						$j('[name="Doituong"]').val(resp.results[0].id);
						$j('[id=Doituong-container-readonly__RAND__]').html('<span class="match-text" id="Doituong-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DOITUONG_view_parent]').hide(); } else { $j('.btn[id=DOITUONG_view_parent]').show(); }

						if(typeof(Doituong_update_autofills__RAND__) == 'function') Doituong_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Doituong__RAND__.value, t: 'STCN', f: 'Doituong' },
				success: function(resp) {
					$j('[id=Doituong-container__RAND__], [id=Doituong-container-readonly__RAND__]').html('<span class="match-text" id="Doituong-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=DOITUONG_view_parent]').hide(); } else { $j('.btn[id=DOITUONG_view_parent]').show(); }

					if(typeof(Doituong_update_autofills__RAND__) == 'function') Doituong_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/STCN_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/STCN_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'STCN details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return STCN_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return STCN_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return STCN_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Sodangki').replaceWith('<div class=\"form-control-static\" id=\"Sodangki\">' + (jQuery('#Sodangki').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Ngaydangki').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaydangki\">' + (jQuery('#Ngaydangki').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Ngaylap').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"Ngaylap\">' + (jQuery('#Ngaylap').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CBLap').replaceWith('<div class=\"form-control-static\" id=\"CBLap\">' + (jQuery('#CBLap').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DVLap').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#DVLap_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#CBQuanly').replaceWith('<div class=\"form-control-static\" id=\"CBQuanly\">' + (jQuery('#CBQuanly').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DVQuanly').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#DVQuanly_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Doituong').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Doituong_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Status').replaceWith('<div class=\"form-control-static\" id=\"Status\">' + (jQuery('#Status').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaydangki').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#Ngaylap').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(DVLap)%%>', $combo_DVLap->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(DVLap)%%>', $combo_DVLap->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(DVLap)%%>', urlencode($combo_DVLap->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(DVQuanly)%%>', $combo_DVQuanly->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(DVQuanly)%%>', $combo_DVQuanly->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(DVQuanly)%%>', urlencode($combo_DVQuanly->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Doituong)%%>', $combo_Doituong->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Doituong)%%>', $combo_Doituong->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Doituong)%%>', urlencode($combo_Doituong->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['DVLap' => ['DONVI', 'DVLap'], 'DVQuanly' => ['DONVI', 'DVQuanly'], 'Doituong' => ['DOITUONG', 'Doituong'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(IDSTCN)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Sodangki)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaydangki)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ngaylap)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CBLap)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DVLap)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CBQuanly)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DVQuanly)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Doituong)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Status)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(IDSTCN)%%>', safe_html($urow['IDSTCN']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(IDSTCN)%%>', html_attr($row['IDSTCN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTCN)%%>', urlencode($urow['IDSTCN']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Sodangki)%%>', safe_html($urow['Sodangki']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Sodangki)%%>', html_attr($row['Sodangki']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Sodangki)%%>', urlencode($urow['Sodangki']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaydangki)%%>', app_datetime($row['Ngaydangki'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaydangki)%%>', urlencode(app_datetime($urow['Ngaydangki'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaylap)%%>', app_datetime($row['Ngaylap'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaylap)%%>', urlencode(app_datetime($urow['Ngaylap'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CBLap)%%>', safe_html($urow['CBLap']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CBLap)%%>', html_attr($row['CBLap']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBLap)%%>', urlencode($urow['CBLap']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DVLap)%%>', safe_html($urow['DVLap']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DVLap)%%>', html_attr($row['DVLap']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DVLap)%%>', urlencode($urow['DVLap']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CBQuanly)%%>', safe_html($urow['CBQuanly']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CBQuanly)%%>', html_attr($row['CBQuanly']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBQuanly)%%>', urlencode($urow['CBQuanly']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(DVQuanly)%%>', safe_html($urow['DVQuanly']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(DVQuanly)%%>', html_attr($row['DVQuanly']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DVQuanly)%%>', urlencode($urow['DVQuanly']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Doituong)%%>', safe_html($urow['Doituong']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Doituong)%%>', html_attr($row['Doituong']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Doituong)%%>', urlencode($urow['Doituong']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', safe_html($urow['Status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Status)%%>', html_attr($row['Status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode($urow['Status']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(IDSTCN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(IDSTCN)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Sodangki)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Sodangki)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaydangki)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaydangki)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ngaylap)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ngaylap)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CBLap)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBLap)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DVLap)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DVLap)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CBQuanly)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CBQuanly)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DVQuanly)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DVQuanly)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Doituong)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Doituong)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('STCN');
	if($selected_id) {
		$jdata = get_joined_record('STCN', $selected_id);
		if($jdata === false) $jdata = get_defaults('STCN');
		$rdata = $row;
	}
	$templateCode .= loadView('STCN-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: STCN_dv
	if(function_exists('STCN_dv')) {
		$args = [];
		STCN_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}