<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/STCNSTT.php');
	include_once(__DIR__ . '/STCNSTT_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('STCNSTT');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'STCNSTT';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`STCNSTT`.`IDSTT`" => "IDSTT",
		"`STCNSTT`.`Phanloai`" => "Phanloai",
		"`STCNSTT`.`Danhmuc`" => "Danhmuc",
		"`STCNSTT`.`Heloai`" => "Heloai",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* IDSTCN */" => "IDSTCN",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`STCNSTT`.`IDSTT`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`STCNSTT`.`IDSTT`" => "IDSTT",
		"`STCNSTT`.`Phanloai`" => "Phanloai",
		"`STCNSTT`.`Danhmuc`" => "Danhmuc",
		"`STCNSTT`.`Heloai`" => "Heloai",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* IDSTCN */" => "IDSTCN",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`STCNSTT`.`IDSTT`" => "ID",
		"`STCNSTT`.`Phanloai`" => "Phanloai",
		"`STCNSTT`.`Danhmuc`" => "Danhmuc",
		"`STCNSTT`.`Heloai`" => "Heloai",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* IDSTCN */" => "IDSTCN",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`STCNSTT`.`IDSTT`" => "IDSTT",
		"`STCNSTT`.`Phanloai`" => "Phanloai",
		"`STCNSTT`.`Danhmuc`" => "Danhmuc",
		"`STCNSTT`.`Heloai`" => "Heloai",
		"IF(    CHAR_LENGTH(`DOITUONG1`.`Hovaten`), CONCAT_WS('',   `DOITUONG1`.`Hovaten`), '') /* IDSTCN */" => "IDSTCN",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['IDSTCN' => 'IDSTCN', ];

	$x->QueryFrom = "`STCNSTT` LEFT JOIN `STCN` as STCN1 ON `STCN1`.`IDSTCN`=`STCNSTT`.`IDSTCN` LEFT JOIN `DOITUONG` as DOITUONG1 ON `DOITUONG1`.`IDDoituong`=`STCN1`.`Doituong` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'STCNSTT_view.php';
	$x->TableTitle = 'STCNSTT';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`STCNSTT`.`IDSTT`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Phanloai', 'Danhmuc', 'Heloai', 'IDSTCN', ];
	$x->ColFieldName = ['Phanloai', 'Danhmuc', 'Heloai', 'IDSTCN', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/STCNSTT_templateTV.html';
	$x->SelectedTemplate = 'templates/STCNSTT_templateTVS.html';
	$x->TemplateDV = 'templates/STCNSTT_templateDV.html';
	$x->TemplateDVP = 'templates/STCNSTT_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: STCNSTT_init
	$render = true;
	if(function_exists('STCNSTT_init')) {
		$args = [];
		$render = STCNSTT_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: STCNSTT_header
	$headerCode = '';
	if(function_exists('STCNSTT_header')) {
		$args = [];
		$headerCode = STCNSTT_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: STCNSTT_footer
	$footerCode = '';
	if(function_exists('STCNSTT_footer')) {
		$args = [];
		$footerCode = STCNSTT_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
