<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/XulyTin.php');
	include_once(__DIR__ . '/XulyTin_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('XulyTin');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'XulyTin';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`XulyTin`.`ID`" => "ID",
		"`XulyTin`.`Xulytin`" => "Xulytin",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`XulyTin`.`ID`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`XulyTin`.`ID`" => "ID",
		"`XulyTin`.`Xulytin`" => "Xulytin",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`XulyTin`.`ID`" => "ID",
		"`XulyTin`.`Xulytin`" => "Xulytin",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`XulyTin`.`ID`" => "ID",
		"`XulyTin`.`Xulytin`" => "Xulytin",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`XulyTin` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'XulyTin_view.php';
	$x->TableTitle = 'XulyTin';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`XulyTin`.`ID`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['ID', 'Xulytin', ];
	$x->ColFieldName = ['ID', 'Xulytin', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/XulyTin_templateTV.html';
	$x->SelectedTemplate = 'templates/XulyTin_templateTVS.html';
	$x->TemplateDV = 'templates/XulyTin_templateDV.html';
	$x->TemplateDVP = 'templates/XulyTin_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: XulyTin_init
	$render = true;
	if(function_exists('XulyTin_init')) {
		$args = [];
		$render = XulyTin_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: XulyTin_header
	$headerCode = '';
	if(function_exists('XulyTin_header')) {
		$args = [];
		$headerCode = XulyTin_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: XulyTin_footer
	$footerCode = '';
	if(function_exists('XulyTin_footer')) {
		$args = [];
		$footerCode = XulyTin_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
